import { supabase } from "@/integrations/supabase/client";

export const hooks150New = [
  // ============================================
  // VERTICAL 1: AUTOMAÇÃO E AGENTES DE IA (50)
  // ============================================
  {
    text: "Seu negócio perde dinheiro por processos manuais?",
    format: "Carrossel",
    pain_point: "Perda de eficiência e lucro",
    emotional_trigger: "Medo / Frustração",
    roteiro: "S1: Título + Imagem de pilhas de papel. S2: Liste 3 tarefas manuais. S3: Calcule o custo de 10h/semana perdidas. S4: IA como solução. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "IA: O segredo do crescimento exponencial",
    format: "Reel",
    pain_point: "Dificuldade em escalar",
    emotional_trigger: "Ambição / Curiosidade",
    roteiro: "0-3s: Gráfico subindo. 3-10s: Narração sobre algoritmos vs pessoas. 10-20s: Prints de dashboards. 20-30s: CTA.",
    vertical: "Automação",
  },
  {
    text: "Atendimento é um gargalo?",
    format: "Carrossel",
    pain_point: "Sobrecarga e clientes insatisfeitos",
    emotional_trigger: "Empatia / Excelência",
    roteiro: "S1: 10 min ou 10 segundos?. S2: Erro humano vs IA. S3: IA resolve 1000 tickets/min. S4: Print real. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Liberte sua equipe para o estratégico",
    format: "Estático",
    pain_point: "Equipe focada no operacional",
    emotional_trigger: "Alívio / Valorização",
    roteiro: "Visual: Foto da equipe criando. Legenda: IA remove o tédio e libera o cérebro humano para gerar lucro real.",
    vertical: "Automação",
  },
  {
    text: "Não seja o último a adotar a IA",
    format: "Carrossel",
    pain_point: "Medo de obsolescência",
    emotional_trigger: "Urgência / Pressão Social",
    roteiro: "S1: Efeito Kodak. S2: Gráfico de adoção de IA. S3: Empresas líderes. S4: A lacuna está aumentando. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Trabalhe menos, produza mais",
    format: "Reel",
    pain_point: "Excesso de trabalho",
    emotional_trigger: "Liberdade / Aspiração",
    roteiro: "Visual: Split screen. Lado A: Trabalho duro. Lado B: IA trabalhando enquanto você descansa.",
    vertical: "Automação",
  },
  {
    text: "Decisões rápidas e precisas?",
    format: "Carrossel",
    pain_point: "Incerteza estratégica",
    emotional_trigger: "Confiança / Controle",
    roteiro: "S1: Feeling ou Fatos?. S2: Vieses humanos. S3: IA e Big Data. S4: Exemplo de previsão de demanda. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Chega de erros humanos!",
    format: "Estático",
    pain_point: "Erros custosos e retrabalho",
    emotional_trigger: "Segurança / Perfeccionismo",
    roteiro: "Visual: Erro em contrato gigante. Legenda: O custo do erro manual vs a segurança da automação.",
    vertical: "Automação",
  },
  {
    text: "O futuro do trabalho: Agentes de IA",
    format: "Reel",
    pain_point: "Processos engessados",
    emotional_trigger: "Curiosidade / Modernidade",
    roteiro: "Visual: Gravação de tela de um Agente de IA navegando e extraindo dados sozinho. Legenda: Isso trabalha enquanto você dorme.",
    vertical: "Automação",
  },
  {
    text: "Sua empresa está pronta?",
    format: "Stories",
    pain_point: "Incerteza tecnológica",
    emotional_trigger: "Desafio / Oportunidade",
    roteiro: "Sequência: 1. Foto servidor. 2. Enquete: 1.0 ou 4.0?. 3. Caixa: Qual processo te trava?.",
    vertical: "Automação",
  },
  {
    text: "Pare de apagar incêndios!",
    format: "Carrossel",
    pain_point: "Reatividade constante",
    emotional_trigger: "Alívio / Proatividade",
    roteiro: "S1: Gestor estressado. S2: Reativa vs Preditiva. S3: IA prevê problemas antes de estourarem. S4: Exemplo. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Otimize seus gastos com a IA",
    format: "Reel",
    pain_point: "Desperdício de recursos",
    emotional_trigger: "Economia / Inteligência",
    roteiro: "Visual: Dinheiro sendo cortado. Texto: Áreas de corte: Logística, Estoque, Energia. Final: Corte desperdício.",
    vertical: "Automação",
  },
  {
    text: "Vendas estagnadas?",
    format: "Carrossel",
    pain_point: "Dificuldade em novos leads",
    emotional_trigger: "Ambição / Superação",
    roteiro: "S1: Funil com furos?. S2: IA analisa comportamento. S3: Lookalike avançado. S4: Venda para quem quer. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Personalização em massa",
    format: "Estático",
    pain_point: "Marketing genérico",
    emotional_trigger: "Exclusividade / Conexão",
    roteiro: "Visual: 100 rostos com ofertas diferentes. Legenda: O fim do marketing genérico. Escala real via IA.",
    vertical: "Automação",
  },
  {
    text: "Segurança de dados e IA",
    format: "Carrossel",
    pain_point: "Medo de ataques",
    emotional_trigger: "Segurança / Tranquilidade",
    roteiro: "S1: Sua empresa protegida?. S2: Hackers usam IA. S3: Detecção em tempo real. S4: Bloqueio. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Contrate com inteligência",
    format: "Reel",
    pain_point: "Seleção demorada",
    emotional_trigger: "Eficiência / Crescimento",
    roteiro: "Visual: Jogando currículos pro alto. Transição: IA organizando ranking. Legenda: Pare de ler currículos irrelevantes.",
    vertical: "Automação",
  },
  {
    text: "Inovação sem limites",
    format: "Carrossel",
    pain_point: "Falta de inspiração",
    emotional_trigger: "Criatividade / Liderança",
    roteiro: "S1: Próximo campeão?. S2: IA analisa reclamações de rivais. S3: Sugestão de novos recursos. S4: Dados. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Dinheiro para a burocracia?",
    format: "Reel",
    pain_point: "Processos lentos",
    emotional_trigger: "Alívio / Descomplicação",
    roteiro: "Visual: Carimbando papéis. Corte: Carimbo vira ícone digital. Legenda: Elimine o imposto sobre a produtividade.",
    vertical: "Automação",
  },
  {
    text: "Cadeia de suprimentos otimizada",
    format: "Carrossel",
    pain_point: "Atrasos na logística",
    emotional_trigger: "Controle / Previsibilidade",
    roteiro: "S1: Entrega atrasada?. S2: Rotas em tempo real. S3: Previsão de demanda regional. S4: Menos km. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Transforme dados em decisões",
    format: "Estático",
    pain_point: "Excesso de dados",
    emotional_trigger: "Clareza / Vantagem",
    roteiro: "Visual: Dashboard minimalista. Legenda: Dados sem análise são apenas ruído. Tenha uma bússola.",
    vertical: "Automação",
  },
  {
    text: "Perdendo clientes para a concorrência?",
    format: "Carrossel",
    pain_point: "Alta taxa de churn",
    emotional_trigger: "Medo / Lealdade",
    roteiro: "S1: Por que eles vão embora?. S2: Sinais detectados por IA. S3: Ações automáticas. S4: Aja antes. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Maximize seu ROI com a IA",
    format: "Reel",
    pain_point: "Investimentos sem retorno",
    emotional_trigger: "Lucratividade / Sucesso",
    roteiro: "Visual: R$ 1 entra, R$ 10 sai. Texto: Otimização em tempo real. Legenda: Explique realocação de verba.",
    vertical: "Automação",
  },
  {
    text: "Otimize sua produção",
    format: "Carrossel",
    pain_point: "Gargalos fabris",
    emotional_trigger: "Perfeição / Reputação",
    roteiro: "S1: Zero defeitos?. S2: Visão computacional. S3: Redução de desperdício. S4: Qualidade total. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Marketing sobrecarregado?",
    format: "Reel",
    pain_point: "Excesso de tarefas",
    emotional_trigger: "Alívio / Criatividade",
    roteiro: "Visual: 50 abas abertas. Ação: IA planeja campanha. Resultado: Plano pronto. Legenda: Superpoderes.",
    vertical: "Automação",
  },
  {
    text: "Trabalho pesado para a IA",
    format: "Carrossel",
    pain_point: "Baixa produtividade",
    emotional_trigger: "Liberdade / Eficiência",
    roteiro: "S1: Gestor ou Digitador?. S2: O que a IA faz melhor. S3: Resumos, e-mails, CRM. S4: Ganhe 2h. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Consultor estratégico no bolso",
    format: "Estático",
    pain_point: "Custo de consultoria",
    emotional_trigger: "Inteligência / Acesso",
    roteiro: "Visual: Smartphone com análise SWOT. Legenda: Conhecimento de 1000 MBAs disponível 24/7.",
    vertical: "Automação",
  },
  {
    text: "Reduza custos operacionais",
    format: "Carrossel",
    pain_point: "Baixa margem de lucro",
    emotional_trigger: "Lucratividade / Sustento",
    roteiro: "S1: Ralo de dinheiro?. S2: Custos invisíveis. S3: Escala sem inchar folha. S4: Lucro real. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Gestão de projetos com IA",
    format: "Reel",
    pain_point: "Atrasos e bagunça",
    emotional_trigger: "Controle / Organização",
    roteiro: "Visual: Gantt se ajustando sozinho. Legenda: O sistema que replaneja imprevistos instantaneamente.",
    vertical: "Automação",
  },
  {
    text: "Preparada para o futuro?",
    format: "Carrossel",
    pain_point: "Medo da obsolescência",
    emotional_trigger: "Visão / Pioneirismo",
    roteiro: "S1: 2026: Ano dos Agentes. S2: Do chat para execução. S3: Seja pioneiro. S4: Vantagem. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Satisfação dos colaboradores",
    format: "Estático",
    pain_point: "Turnover alto",
    emotional_trigger: "Bem-estar / Engajamento",
    roteiro: "Visual: Alguém saindo cedo sorrindo. Legenda: Trabalho inteligente. IA libera o humano.",
    vertical: "Automação",
  },
  {
    text: "Desvende o consumidor",
    format: "Carrossel",
    pain_point: "Falta de entendimento",
    emotional_trigger: "Poder / Conhecimento",
    roteiro: "S1: O que ele faz no escuro?. S2: Mapas de calor. S3: Por que abandonam? S4: Ciência da venda. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Infraestrutura de TI moderna",
    format: "Reel",
    pain_point: "Sistemas lentos",
    emotional_trigger: "Modernidade / Segurança",
    roteiro: "Visual: Servidores neon. Legenda: Manutenção preditiva: O sistema que se cura.",
    vertical: "Automação",
  },
  {
    text: "Experiências memoráveis",
    format: "Carrossel",
    pain_point: "Baixa fidelidade",
    emotional_trigger: "Encantamento / Lealdade",
    roteiro: "S1: Por que não voltam?. S2: Falta de personalização. S3: Recepção VIP via IA. S4: Encantamento. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Vantagem competitiva secreta",
    format: "Estático",
    pain_point: "Perda de mercado",
    emotional_trigger: "Vitória / Liderança",
    roteiro: "Visual: Rainha dominando xadrez. Legenda: IA muda todas as regras do jogo.",
    vertical: "Automação",
  },
  {
    text: "Automatize tarefas chatas",
    format: "Reel",
    pain_point: "Perda de tempo",
    emotional_trigger: "Realização / Liberdade",
    roteiro: "Visual: Bot preenchendo planilha via foto. Legenda: Nunca mais digite um recibo.",
    vertical: "Automação",
  },
  {
    text: "Gestão financeira com IA",
    format: "Carrossel",
    pain_point: "Desorganização financeira",
    emotional_trigger: "Tranquilidade / Controle",
    roteiro: "S1: Cadê o lucro?. S2: Categorização automática. S3: Alertas de duplicidade. S4: Piloto automático. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "IA na saúde",
    format: "Estático",
    pain_point: "Diagnósticos lentos",
    emotional_trigger: "Esperança / Cuidado",
    roteiro: "Visual: Médico com tablet gráfico. Legenda: Diagnósticos em segundos que salvam vidas.",
    vertical: "Automação",
  },
  {
    text: "Atendimento como diferencial",
    format: "Reel",
    pain_point: "Suporte demorado",
    emotional_trigger: "Excelência / Satisfação",
    roteiro: "Visual: Bot resolvendo problema rápido. Legenda: Suporte 24/7 que resolve.",
    vertical: "Automação",
  },
  {
    text: "Estoque inteligente",
    format: "Carrossel",
    pain_point: "Ruptura de estoque",
    emotional_trigger: "Lucratividade / Eficiência",
    roteiro: "S1: Ruptura ou excesso?. S2: Previsão sazonal. S3: Reabastecimento automático. S4: Giro. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "IA no setor jurídico",
    format: "Estático",
    pain_point: "Análise lenta de documentos",
    emotional_trigger: "Justiça / Modernização",
    roteiro: "Visual: Balança digital. Legenda: Menos leitura de petições, mais estratégia.",
    vertical: "Automação",
  },
  {
    text: "Potencial da equipe",
    format: "Carrossel",
    pain_point: "Treinamento ineficaz",
    emotional_trigger: "Crescimento / Valorização",
    roteiro: "S1: Treino genérico?. S2: Trilhas via IA. S3: Maximizando talento. S4: Alta performance. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "IA na educação",
    format: "Reel",
    pain_point: "Ensino padronizado",
    emotional_trigger: "Futuro / Progresso",
    roteiro: "Visual: Tutor virtual ensinando. Legenda: Aprendizado adaptativo: O futuro.",
    vertical: "Automação",
  },
  {
    text: "Gestão de frotas",
    format: "Carrossel",
    pain_point: "Custos de combustível",
    emotional_trigger: "Segurança / Economia",
    roteiro: "S1: Custos de combustível?. S2: Monitoramento de motorista. S3: Rotas inteligentes. S4: Economia. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Oportunidades de mercado",
    format: "Estático",
    pain_point: "Dificuldade em nichos",
    emotional_trigger: "Descoberta / Inovação",
    roteiro: "Visual: Mapa com pontos brilhantes. Legenda: IA mapeou 3 nichos inexplorados.",
    vertical: "Automação",
  },
  {
    text: "Automação de marketing",
    format: "Reel",
    pain_point: "Baixo engajamento",
    emotional_trigger: "Reconhecimento / Sucesso",
    roteiro: "Visual: Criando 100 anúncios em 1 min. Legenda: Campanhas inteligentes.",
    vertical: "Automação",
  },
  {
    text: "IA na agricultura",
    format: "Carrossel",
    pain_point: "Baixa produtividade",
    emotional_trigger: "Sustentabilidade / Abundância",
    roteiro: "S1: Colheita produtiva?. S2: Drones e sensores. S3: Otimização. S4: Lucro verde. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Proteção contra fraudes",
    format: "Estático",
    pain_point: "Perdas financeiras",
    emotional_trigger: "Proteção / Segurança",
    roteiro: "Visual: Escudo digital. Legenda: IA barrou R$ 100k em fraudes.",
    vertical: "Automação",
  },
  {
    text: "RH estratégico",
    format: "Carrossel",
    pain_point: "Seleção lenta",
    emotional_trigger: "Eficiência / Crescimento",
    roteiro: "S1: Seleção lenta?. S2: Triagem por fit. S3: Fim do currículo inútil. S4: Contratação certa. S5: CTA.",
    vertical: "Automação",
  },
  {
    text: "Varejo omnichannel",
    format: "Reel",
    pain_point: "Compra desconectada",
    emotional_trigger: "Conveniência / Satisfação",
    roteiro: "Visual: Compra online, retira na loja. Legenda: Experiência fluida.",
    vertical: "Automação",
  },
  {
    text: "Era dos Agentes de IA",
    format: "Carrossel",
    pain_point: "Medo do futuro",
    emotional_trigger: "Liderança / Preparação",
    roteiro: "S1: Pronto para 2026?. S2: Checklist de implementação. S3: Cultura AI-First. S4: Lidere. S5: CTA.",
    vertical: "Automação",
  },

  // ============================================
  // VERTICAL 2: DESENVOLVIMENTO E E-COMMERCE (50)
  // ============================================
  {
    text: "Seu site não vende?",
    format: "Carrossel",
    pain_point: "Baixas vendas e UX ruim",
    emotional_trigger: "Frustração / Sucesso",
    roteiro: "S1: Cemitério de e-commerces. S2: Confuso vs Limpo. S3: Confiança de Kahneman. S4: Auditoria. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Chega de sistemas engessados!",
    format: "Reel",
    pain_point: "Ineficiência operacional",
    emotional_trigger: "Controle / Otimização",
    roteiro: "Visual: Luta com software antigo vs novo fluindo. Legenda: Software que se molda a você.",
    vertical: "Dev",
  },
  {
    text: "E-commerce pronto para o futuro?",
    format: "Carrossel",
    pain_point: "Dificuldade em escalar",
    emotional_trigger: "Ambição / Urgência",
    roteiro: "S1: Sua escala é real?. S2: Tecnologia para 10x vendas. S3: Infra elástica. S4: Estabilidade. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Ideia em realidade digital",
    format: "Estático",
    pain_point: "Projetos no papel",
    emotional_trigger: "Realização / Confiança",
    roteiro: "Visual: Foto de código limpo. Legenda: Do guardanapo para o deploy.",
    vertical: "Dev",
  },
  {
    text: "Checkout complicado mata vendas",
    format: "Reel",
    pain_point: "Abandono de carrinho",
    emotional_trigger: "Facilidade / Agilidade",
    roteiro: "Visual: Pessoa desistindo por excesso de campos. Legenda: Simplifique ou perca lucro.",
    vertical: "Dev",
  },
  {
    text: "Gestão é um pesadelo?",
    format: "Carrossel",
    pain_point: "Desorganização total",
    emotional_trigger: "Alívio / Eficiência",
    roteiro: "S1: Paz operacional. S2: Planilhas vs Dashboard. S3: Organização. S4: Depoimento. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Vende 24h por dia",
    format: "Estático",
    pain_point: "Dependência de horário",
    emotional_trigger: "Liberdade / Expansão",
    roteiro: "Visual: Loja fechada vs E-commerce bombando. Legenda: Sua loja nunca fecha.",
    vertical: "Dev",
  },
  {
    text: "Por onde começar?",
    format: "Carrossel",
    pain_point: "Incerteza técnica",
    emotional_trigger: "Segurança / Clareza",
    roteiro: "S1: Mapa do desenvolvimento. S2: Da ideia ao lançamento. S3: Consultoria. S4: Segurança. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Sistemas inteligentes",
    format: "Reel",
    pain_point: "Processos lentos",
    emotional_trigger: "Inteligência / Progresso",
    roteiro: "Visual: Estoque integrando sozinho. Legenda: Trabalhe menos, produza mais.",
    vertical: "Dev",
  },
  {
    text: "Seu e-commerce é seguro?",
    format: "Carrossel",
    pain_point: "Medo de ataques",
    emotional_trigger: "Segurança / Confiança",
    roteiro: "S1: 3 selos de segurança. S2: Confiança vende. S3: Proteção de dados. S4: Checklist. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Dados em lucro (BI)",
    format: "Estático",
    pain_point: "Decisões no achismo",
    emotional_trigger: "Poder / Vantagem",
    roteiro: "Visual: Gráfico de BI mudando rumo. Legenda: Decisões no achismo custam caro.",
    vertical: "Dev",
  },
  {
    text: "App dos sonhos",
    format: "Reel",
    pain_point: "Falta de presença mobile",
    emotional_trigger: "Modernidade / Sucesso",
    roteiro: "Visual: Fluidez de app nativo. Legenda: Sua marca no bolso do cliente.",
    vertical: "Dev",
  },
  {
    text: "E-commerce B2B",
    format: "Carrossel",
    pain_point: "Processos B2B lentos",
    emotional_trigger: "Profissionalismo / Eficiência",
    roteiro: "S1: Venda para empresas. S2: Portal agiliza pedidos. S3: Gestão de catálogos. S4: Rapidez. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Modernize seu legado",
    format: "Estático",
    pain_point: "Servidores lentos",
    emotional_trigger: "Alívio / Modernidade",
    roteiro: "Visual: Servidor físico vs Cloud. Legenda: O risco de ficar no passado.",
    vertical: "Dev",
  },
  {
    text: "MVP de sucesso",
    format: "Carrossel",
    pain_point: "Medo de investir e falhar",
    emotional_trigger: "Oportunidade / Agilidade",
    roteiro: "S1: Valide rápido. S2: Startup em 60 dias. S3: Foco no essencial. S4: Economia. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Gestão de estoque",
    format: "Reel",
    pain_point: "Prejuízo com estoque parado",
    emotional_trigger: "Lucratividade / Controle",
    roteiro: "Visual: Sistema avisando quando liquidar. Legenda: Nunca mais perca dinheiro parado.",
    vertical: "Dev",
  },
  {
    text: "Portal do cliente",
    format: "Carrossel",
    pain_point: "Suporte sobrecarregado",
    emotional_trigger: "Exclusividade / Satisfação",
    roteiro: "S1: Autoatendimento. S2: Cliente resolve sozinho. S3: Histórico. S4: Exclusividade. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Automação interna",
    format: "Reel",
    pain_point: "Desperdício de tempo",
    emotional_trigger: "Eficiência / Produtividade",
    roteiro: "Visual: 4h virando 4 segundos. Legenda: Eficiência real.",
    vertical: "Dev",
  },
  {
    text: "Mais tráfego",
    format: "Carrossel",
    pain_point: "Baixa visibilidade",
    emotional_trigger: "Crescimento / Reconhecimento",
    roteiro: "S1: SEO técnico. S2: Dicas para produtos. S3: Visibilidade orgânica. S4: Sucesso. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "APIs: Integre tudo",
    format: "Estático",
    pain_point: "Sistemas isolados",
    emotional_trigger: "Conectividade / Inteligência",
    roteiro: "Visual: ERP falando com Site. Legenda: Conectividade total.",
    vertical: "Dev",
  },
  {
    text: "UX impecável",
    format: "Carrossel",
    pain_point: "Clientes frustrados",
    emotional_trigger: "Excelência / Lealdade",
    roteiro: "S1: Psicologia do clique. S2: Cores e botões. S3: Retenção. S4: Excelência. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "CRM vs Planilhas",
    format: "Reel",
    pain_point: "Perda de dados",
    emotional_trigger: "Controle / Organização",
    roteiro: "Visual: Vendedor perdido vs CRM avisando. Legenda: Controle seus leads.",
    vertical: "Dev",
  },
  {
    text: "App que engaja",
    format: "Carrossel",
    pain_point: "Apps pouco usados",
    emotional_trigger: "Sucesso / Conexão",
    roteiro: "S1: 5 funções essenciais. S2: Retenção. S3: Notificações. S4: Sucesso. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Projetos sem estresse",
    format: "Estático",
    pain_point: "Atrasos constantes",
    emotional_trigger: "Organização / Segurança",
    roteiro: "Visual: Prazos são sagrados. Legenda: Como garantimos a entrega.",
    vertical: "Dev",
  },
  {
    text: "Estabilidade total",
    format: "Carrossel",
    pain_point: "Quedas em picos",
    emotional_trigger: "Segurança / Confiança",
    roteiro: "S1: Picos de venda. S2: Black Friday sem queda. S3: Infra elástica. S4: Segurança. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Plataformas EAD",
    format: "Reel",
    pain_point: "Alcance limitado",
    emotional_trigger: "Impacto / Expansão",
    roteiro: "Visual: Curso presencial virando digital. Legenda: Escala seu conhecimento.",
    vertical: "Dev",
  },
  {
    text: "Automação de vendas",
    format: "Carrossel",
    pain_point: "Time comercial lento",
    emotional_trigger: "Lucratividade / Rapidez",
    roteiro: "S1: Proposta automática. S2: Vendedor só fecha. S3: Lucratividade. S4: Rapidez. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Sistemas modulares",
    format: "Estático",
    pain_point: "Dificuldade em crescer",
    emotional_trigger: "Praticidade / Visão",
    roteiro: "Visual: Comece pequeno, cresça gigante. Legenda: Sistemas que evoluem.",
    vertical: "Dev",
  },
  {
    text: "Diferencial competitivo",
    format: "Carrossel",
    pain_point: "Concorrência forte",
    emotional_trigger: "Inovação / Liderança",
    roteiro: "S1: Inove no e-commerce. S2: Provador virtual. S3: Experiência única. S4: Liderança. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Gestão financeira",
    format: "Reel",
    pain_point: "Fluxo nebuloso",
    emotional_trigger: "Tranquilidade / Controle",
    roteiro: "Visual: Relatório no WhatsApp. Legenda: Tranquilidade pro dono.",
    vertical: "Dev",
  },
  {
    text: "Velocidade é dinheiro",
    format: "Carrossel",
    pain_point: "Abandono por lentidão",
    emotional_trigger: "Urgência / Eficiência",
    roteiro: "S1: 30% mais vendas. S2: Otimização de carga. S3: Abandono. S4: Urgência. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Crie um Marketplace",
    format: "Estático",
    pain_point: "Gestão complexa",
    emotional_trigger: "Liderança / Ambição",
    roteiro: "Visual: Seja o Amazon do nicho. Legenda: Múltiplos sellers, um lucro.",
    vertical: "Dev",
  },
  {
    text: "Site não responsivo?",
    format: "Reel",
    pain_point: "Perda mobile",
    emotional_trigger: "Modernidade / Relevância",
    roteiro: "Visual: Site quebrando no celular. Legenda: Modernize sua presença.",
    vertical: "Dev",
  },
  {
    text: "Agendamento online",
    format: "Carrossel",
    pain_point: "Telefone tocando",
    emotional_trigger: "Conveniência / Alívio",
    roteiro: "S1: Fim do telefone. S2: Agenda 2h da manhã. S3: Conveniência. S4: Organização. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Realidade Aumentada",
    format: "Reel",
    pain_point: "Dúvida de produto",
    emotional_trigger: "Encantamento / Certeza",
    roteiro: "Visual: Sofá virtual na sala real. Legenda: Encante e venda.",
    vertical: "Dev",
  },
  {
    text: "Intranet moderna",
    format: "Carrossel",
    pain_point: "Comunicação falha",
    emotional_trigger: "Pertencimento / Ordem",
    roteiro: "S1: Equipe conectada. S2: Central de conhecimento. S3: Fim da desinformação. S4: Ordem. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "CMS: Autonomia",
    format: "Estático",
    pain_point: "Dependência técnica",
    emotional_trigger: "Autonomia / Poder",
    roteiro: "Visual: Mude tudo em segundos. Legenda: Sem saber código.",
    vertical: "Dev",
  },
  {
    text: "Topo do Google",
    format: "Carrossel",
    pain_point: "Baixo tráfego",
    emotional_trigger: "Reconhecimento / Sucesso",
    roteiro: "S1: Checklist SEO. S2: O que o site precisa. S3: Tráfego. S4: Sucesso. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Gamificação",
    format: "Reel",
    pain_point: "Falta de motivação",
    emotional_trigger: "Recompensa / Diversão",
    roteiro: "Visual: Cliente ganhando pontos. Legenda: Fidelize comprando.",
    vertical: "Dev",
  },
  {
    text: "Gestão de documentos",
    format: "Carrossel",
    pain_point: "Papelada física",
    emotional_trigger: "Segurança / Organização",
    roteiro: "S1: Ache em 3 segundos. S2: Fim da papelada. S3: Segurança digital. S4: Ordem. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "App para equipes",
    format: "Estático",
    pain_point: "Falta de controle",
    emotional_trigger: "Controle / Eficiência",
    roteiro: "Visual: Gestão na palma da mão. Legenda: Controle de campo.",
    vertical: "Dev",
  },
  {
    text: "E-commerce com IA",
    format: "Carrossel",
    pain_point: "Recomendações ruins",
    emotional_trigger: "Exclusividade / Conexão",
    roteiro: "S1: Recomendações 2.0. S2: Personalização real. S3: Venda cruzada. S4: Exclusividade. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "CRM para fidelizar",
    format: "Reel",
    pain_point: "Esquecimento de clientes",
    emotional_trigger: "Lealdade / Cuidado",
    roteiro: "Visual: Hora de ligar pro cliente. Legenda: Lealdade extrema.",
    vertical: "Dev",
  },
  {
    text: "Mobile-First",
    format: "Carrossel",
    pain_point: "Sites pesados",
    emotional_trigger: "Modernidade / Performance",
    roteiro: "S1: Celular antes do PC. S2: Design estratégico. S3: Modernidade. S4: Performance. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Gestão de assinaturas",
    format: "Estático",
    pain_point: "Receita instável",
    emotional_trigger: "Previsibilidade / Segurança",
    roteiro: "Visual: Meta batida no dia 1. Legenda: Previsibilidade.",
    vertical: "Dev",
  },
  {
    text: "E-learning empresas",
    format: "Carrossel",
    pain_point: "Treinamento lento",
    emotional_trigger: "Crescimento / Eficácia",
    roteiro: "S1: Onboarding 2 dias. S2: Treino automatizado. S3: Crescimento. S4: Eficácia. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Checkout ultrarrápido",
    format: "Reel",
    pain_point: "Perda no final",
    emotional_trigger: "Agilidade / Satisfação",
    roteiro: "Visual: Compra em 1 clique. Legenda: Agilidade total.",
    vertical: "Dev",
  },
  {
    text: "Pagamentos flexíveis",
    format: "Carrossel",
    pain_point: "Falta de opções",
    emotional_trigger: "Satisfação / Liberdade",
    roteiro: "S1: Pix, Cripto e mais. S2: Não perca venda. S3: Satisfação. S4: Flexibilidade. S5: CTA.",
    vertical: "Dev",
  },
  {
    text: "Gestão de eventos",
    format: "Estático",
    pain_point: "Inscrições manuais",
    emotional_trigger: "Sucesso / Organização",
    roteiro: "Visual: Evento sem planilhas. Legenda: Sucesso absoluto.",
    vertical: "Dev",
  },
  {
    text: "Blog que vende",
    format: "Carrossel",
    pain_point: "Conteúdo inútil",
    emotional_trigger: "Autoridade / Conversão",
    roteiro: "S1: Conteúdo estratégico. S2: Leitores em compradores. S3: Autoridade. S4: Sucesso. S5: CTA.",
    vertical: "Dev",
  },

  // ============================================
  // VERTICAL 3: STUDIO CRIATIVO COM IA (50)
  // ============================================
  {
    text: "Campanha invisível?",
    format: "Reel",
    pain_point: "Baixo engajamento",
    emotional_trigger: "Reconhecimento / Sucesso",
    roteiro: "0-1s: Explosão cores IA. Legenda: Se não parou o scroll, falhou. Garantimos impacto.",
    vertical: "Studio",
  },
  {
    text: "Chega de publicidade genérica",
    format: "Carrossel",
    pain_point: "Falta de conexão",
    emotional_trigger: "Autenticidade / Conexão",
    roteiro: "S1: Publicidade com alma. S2: Comum vs IA. S3: Emoção. S4: Autenticidade. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "O futuro é agora",
    format: "Estático",
    pain_point: "Campanhas ineficazes",
    emotional_trigger: "Visão / Pioneirismo",
    roteiro: "Visual: Foto futurista IA. Legenda: Nova era: Onde dados viram arte.",
    vertical: "Studio",
  },
  {
    text: "História épica da marca",
    format: "Reel",
    pain_point: "Dificuldade em contar",
    emotional_trigger: "Inspiração / Emoção",
    roteiro: "Visual: Trailer cinema IA. Legenda: Não venda produtos, venda jornadas.",
    vertical: "Studio",
  },
  {
    text: "Fim dos brainstormings",
    format: "Carrossel",
    pain_point: "Bloqueio criativo",
    emotional_trigger: "Agilidade / Alívio",
    roteiro: "S1: 50 conceitos em 5 min. S2: Processo acelerado. S3: Diversidade. S4: Agilidade. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Personalização em escala",
    format: "Reel",
    pain_point: "Criativos genéricos",
    emotional_trigger: "Conexão / Exclusividade",
    roteiro: "Visual: IA mudando fundo. Legenda: Um anúncio para cada cidade.",
    vertical: "Studio",
  },
  {
    text: "Orçamento limitado?",
    format: "Carrossel",
    pain_point: "Custos altos",
    emotional_trigger: "Economia / Inteligência",
    roteiro: "S1: Comercial de R$ 50k por menos. S2: Corte de custos. S3: Eficiência. S4: Inteligência. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Anúncios que ninguém ignora",
    format: "Reel",
    pain_point: "Baixa atenção",
    emotional_trigger: "Sucesso / Poder",
    roteiro: "Visual: Psicologia visual. Legenda: 3 segredos para prender o olhar.",
    vertical: "Studio",
  },
  {
    text: "Inove ou morra",
    format: "Estático",
    pain_point: "Estagnação",
    emotional_trigger: "Urgência / Liderança",
    roteiro: "Visual: Tradicional vs IA. Legenda: Não fique em 2010.",
    vertical: "Studio",
  },
  {
    text: "Dados em arte",
    format: "Carrossel",
    pain_point: "Campanhas sem base",
    emotional_trigger: "Clareza / Inteligência",
    roteiro: "S1: Insight criativo. S2: Dados guiam estética. S3: Inteligência. S4: Clareza. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Produção ultrarrápida",
    format: "Reel",
    pain_point: "Prazos apertados",
    emotional_trigger: "Modernidade / Agilidade",
    roteiro: "Visual: Timelapse vídeo IA. Legenda: Modernidade e pressa.",
    vertical: "Studio",
  },
  {
    text: "Criativos para cada plataforma",
    format: "Carrossel",
    pain_point: "Retrabalho",
    emotional_trigger: "Versatilidade / Eficiência",
    roteiro: "S1: TikTok, YT, Stories. S2: Adaptação IA. S3: Versatilidade. S4: Eficiência. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Voz única da marca",
    format: "Estático",
    pain_point: "Identidade verbal fraca",
    emotional_trigger: "Originalidade / Reconhecimento",
    roteiro: "Visual: Qual seu tom?. Legenda: Identidade potente.",
    vertical: "Studio",
  },
  {
    text: "Campanhas que leem a mente",
    format: "Reel",
    pain_point: "Baixa conversão",
    emotional_trigger: "Surpresa / Conexão",
    roteiro: "Visual: IA prevendo desejo. Legenda: Conexão antes do clique.",
    vertical: "Studio",
  },
  {
    text: "Edição em minutos",
    format: "Carrossel",
    pain_point: "Pós-produção lenta",
    emotional_trigger: "Produtividade / Alívio",
    roteiro: "S1: Edição rápida. S2: Remoção silêncios. S3: Produtividade. S4: Foco. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Personagens incríveis",
    format: "Reel",
    pain_point: "Limitações de locação",
    emotional_trigger: "Fantasia / Inovação",
    roteiro: "Visual: Comercial em Marte. Legenda: Limites só na imaginação.",
    vertical: "Studio",
  },
  {
    text: "Publicidade gera leads",
    format: "Carrossel",
    pain_point: "Campanhas inúteis",
    emotional_trigger: "Lucratividade / Sucesso",
    roteiro: "S1: Bonita e Útil. S2: Estética vs Conversão. S3: ROI. S4: Sucesso. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Cinema para PMEs",
    format: "Reel",
    pain_point: "Falta de recursos",
    emotional_trigger: "Ambição / Acesso",
    roteiro: "Visual: Vídeo épico barato. Legenda: Vídeo épico para todos.",
    vertical: "Studio",
  },
  {
    text: "O que o público quer ver?",
    format: "Carrossel",
    pain_point: "Conteúdo irrelevante",
    emotional_trigger: "Controle / Conhecimento",
    roteiro: "S1: Tendências IA. S2: IA guia conteúdo. S3: Relevância. S4: Controle. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Campanhas virais",
    format: "Reel",
    pain_point: "Baixo alcance",
    emotional_trigger: "Popularidade / Sucesso",
    roteiro: "Visual: Gatilhos virais. Legenda: O segredo do buzz.",
    vertical: "Studio",
  },
  {
    text: "Jingles inesquecíveis",
    format: "Estático",
    pain_point: "Falta de som",
    emotional_trigger: "Emoção / Reconhecimento",
    roteiro: "Visual: Sua marca tem som?. Legenda: Identidade sonora.",
    vertical: "Studio",
  },
  {
    text: "Mídia inteligente",
    format: "Carrossel",
    pain_point: "Investimento errado",
    emotional_trigger: "Precisão / Lucratividade",
    roteiro: "S1: Onde e quando. S2: Otimização verba. S3: Precisão. S4: Lucro. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Vídeo que converte",
    format: "Reel",
    pain_point: "Falta de vendas",
    emotional_trigger: "Profissionalismo / Sucesso",
    roteiro: "Visual: Estrutura VSL. Legenda: Abra a carteira do cliente.",
    vertical: "Studio",
  },
  {
    text: "Marca atualizada",
    format: "Carrossel",
    pain_point: "Visual datado",
    emotional_trigger: "Relevância / Modernidade",
    roteiro: "S1: Tendências 2026. S2: Estéticas futuras. S3: Liderança. S4: Relevância. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Automação de design",
    format: "Reel",
    pain_point: "Sobrecarga",
    emotional_trigger: "Alívio / Criatividade",
    roteiro: "Visual: 10 posts segundos. Legenda: Alívio criativo.",
    vertical: "Studio",
  },
  {
    text: "IA Diretor de Arte",
    format: "Carrossel",
    pain_point: "Falta de sênior",
    emotional_trigger: "Exclusividade / Beleza",
    roteiro: "S1: Nível sênior. S2: Conceitos únicos. S3: Beleza. S4: Estratégia. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Influenciadores perfeitos",
    format: "Estático",
    pain_point: "Parceiros errados",
    emotional_trigger: "Autenticidade / Confiança",
    roteiro: "Visual: Afinidade real. Legenda: IA escolhe por você.",
    vertical: "Studio",
  },
  {
    text: "Logos memoráveis",
    format: "Carrossel",
    pain_point: "Falta de impacto",
    emotional_trigger: "Reconhecimento / Orgulho",
    roteiro: "S1: Semiologia IA. S2: Fixação mente. S3: Reconhecimento. S4: Orgulho. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Engajamento e conversão",
    format: "Reel",
    pain_point: "Baixa interação",
    emotional_trigger: "Sucesso / Conexão",
    roteiro: "Visual: Legendas magnéticas. Legenda: Faça eles comentarem.",
    vertical: "Studio",
  },
  {
    text: "Experiências imersivas",
    format: "Carrossel",
    pain_point: "Publicidade chata",
    emotional_trigger: "Encantamento / Inovação",
    roteiro: "S1: Filtros vendem. S2: Interação 3D. S3: Encantamento. S4: Inovação. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "E-mail que converte",
    format: "Estático",
    pain_point: "Baixa abertura",
    emotional_trigger: "Eficiência / Sucesso",
    roteiro: "Visual: Assunto é tudo. Legenda: Otimização IA.",
    vertical: "Studio",
  },
  {
    text: "Apresentações de impacto",
    format: "Carrossel",
    pain_point: "Slides chatos",
    emotional_trigger: "Sucesso / Poder",
    roteiro: "S1: Decks épicos. S2: Storytelling. S3: Impressione. S4: Sucesso. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Comunicação interna",
    format: "Reel",
    pain_point: "Equipe desligada",
    emotional_trigger: "Clareza / Engajamento",
    roteiro: "Visual: Treino divertido. Legenda: Clareza total.",
    vertical: "Studio",
  },
  {
    text: "Mascotes únicos",
    format: "Carrossel",
    pain_point: "Falta de carisma",
    emotional_trigger: "Carisma / Conexão",
    roteiro: "S1: Humanize IA. S2: Consistência. S3: Carisma. S4: Conexão. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Destaque no feed",
    format: "Reel",
    pain_point: "Público ignora",
    emotional_trigger: "Visibilidade / Poder",
    roteiro: "Visual: Pattern Interrupt. Legenda: O 1º segundo.",
    vertical: "Studio",
  },
  {
    text: "Tours Virtuais",
    format: "Carrossel",
    pain_point: "Dificuldade local",
    emotional_trigger: "Conveniência / Inovação",
    roteiro: "S1: Venda de casa. S2: 360º. S3: Conveniência. S4: Inovação. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "SEO via IA",
    format: "Estático",
    pain_point: "Falta tráfego",
    emotional_trigger: "Reconhecimento / Autoridade",
    roteiro: "Visual: Escreva humanos. Legenda: Otimize robôs.",
    vertical: "Studio",
  },
  {
    text: "Vídeos explicativos",
    format: "Reel",
    pain_point: "Produto difícil",
    emotional_trigger: "Clareza / Alívio",
    roteiro: "Visual: Animação 15s. Legenda: Simplifique tudo.",
    vertical: "Studio",
  },
  {
    text: "Slogans que vendem",
    format: "Carrossel",
    pain_point: "Frases fracas",
    emotional_trigger: "Identidade / Reconhecimento",
    roteiro: "S1: Taglines. S2: Fórmulas. S3: Identidade. S4: Sucesso. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Eventos interativos",
    format: "Reel",
    pain_point: "Stand vazio",
    emotional_trigger: "Destaque / Curiosidade",
    roteiro: "Visual: IA no stand. Legenda: Atraia no físico.",
    vertical: "Studio",
  },
  {
    text: "Toque humano voz",
    format: "Carrossel",
    pain_point: "Voz robótica",
    emotional_trigger: "Autenticidade / Conexão",
    roteiro: "S1: Emoção natural. S2: Voz certa. S3: Autenticidade. S4: Conexão. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Impacto Social",
    format: "Reel",
    pain_point: "Falta mobilização",
    emotional_trigger: "Empatia / Propósito",
    roteiro: "Visual: Vídeos tocam. Legenda: Empatia e ação.",
    vertical: "Studio",
  },
  {
    text: "Redes estratégicas",
    format: "Carrossel",
    pain_point: "Posts sem rumo",
    emotional_trigger: "Eficiência / Sucesso",
    roteiro: "S1: Calendário. S2: Frequência. S3: Eficiência. S4: Sucesso. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Identidade 360º",
    format: "Estático",
    pain_point: "Marca bagunçada",
    emotional_trigger: "Modernidade / Ordem",
    roteiro: "Visual: Sem logo. Legenda: Modernidade total.",
    vertical: "Studio",
  },
  {
    text: "Viralização TikTok",
    format: "Reel",
    pain_point: "Baixo alcance",
    emotional_trigger: "Popularidade / Sucesso",
    roteiro: "Visual: Desafio 7 dias. Legenda: Alcance massivo.",
    vertical: "Studio",
  },
  {
    text: "Publicidade insights",
    format: "Carrossel",
    pain_point: "Falta dados",
    emotional_trigger: "Inteligência / Poder",
    roteiro: "S1: Big Data diz. S2: Cliente ideal. S3: Inteligência. S4: Poder. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Podcasts marca",
    format: "Reel",
    pain_point: "Difícil áudio",
    emotional_trigger: "Conexão / Inovação",
    roteiro: "Visual: Sem estúdio. Legenda: Conexão áudio.",
    vertical: "Studio",
  },
  {
    text: "Storytelling emoção",
    format: "Carrossel",
    pain_point: "Marca fria",
    emotional_trigger: "Inspiração / Emoção",
    roteiro: "S1: Herói. S2: Inspiradora. S3: Profunda. S4: Inspiração. S5: CTA.",
    vertical: "Studio",
  },
  {
    text: "Anúncios Streaming",
    format: "Estático",
    pain_point: "Novos canais",
    emotional_trigger: "Alcance / Modernidade",
    roteiro: "Visual: Netflix. Legenda: Alcance premium.",
    vertical: "Studio",
  },
  {
    text: "Manifesto IA",
    format: "Carrossel",
    pain_point: "Medo futuro",
    emotional_trigger: "Liderança / Visão",
    roteiro: "S1: Por que IA. S2: Futuro. S3: Liderança. S4: Visão. S5: CTA.",
    vertical: "Studio",
  },
];

export async function seed150HooksNew(workspaceId: string) {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error("User not authenticated");

    console.log("🗑️ Deletando hooks existentes...");
    await supabase
      .from("hooks")
      .delete()
      .eq("workspace_id", workspaceId);

    console.log("📝 Inserindo 150 hooks novos...");

    // Inserir em lotes de 5
    for (let i = 0; i < hooks150New.length; i += 5) {
      const batch = hooks150New.slice(i, i + 5);

      const hooksToInsert = batch.map((hook) => ({
        workspace_id: workspaceId,
        text: hook.text,
        format: hook.format,
        pain_point: hook.pain_point,
        emotional_trigger: hook.emotional_trigger,
        roteiro: hook.roteiro,
        vertical: hook.vertical,
        created_by: user.id,
        views: Math.floor(Math.random() * 9000) + 1000,
        times_used: Math.floor(Math.random() * 25),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }));

      const { error } = await supabase
        .from("hooks")
        .insert(hooksToInsert);

      if (error) {
        console.error(`Erro ao inserir lote ${Math.floor(i / 5) + 1}:`, error);
        throw error;
      }

      console.log(`✅ Lote ${Math.floor(i / 5) + 1} inserido (${Math.min(i + 5, hooks150New.length)}/${hooks150New.length})`);
    }

    console.log("✅ Todos os 150 hooks foram importados com sucesso!");
    return true;
  } catch (error) {
    console.error("❌ Erro ao importar hooks:", error);
    throw error;
  }
}
