// 150 Hooks estratégicos extraídos do documento oficial
// Organizados em 3 verticais com os 4 campos obrigatórios:
// - Hook/Gancho (título)
// - Dor que Resolve
// - Gatilho Emocional
// - Descrição do Conteúdo

import { supabase } from "@/integrations/supabase/client";
import type { CreateHookInput } from "@/types/hooks";

const hooks150Complete: CreateHookInput[] = [
  // VERTICAL 1: AUTOMAÇÃO E AGENTES DE IA (50 hooks)
  {
    text: "Seu negócio está perdendo dinheiro por processos manuais?",
    template: "Pergunta provocadora + Comparativo",
    pain_point: "Perda de eficiência e lucro devido a tarefas repetitivas",
    emotional_trigger: "Medo de ficar para trás / Frustração",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Carrossel",
    visual_mode: "Clean",
  },
  {
    text: "IA: O segredo dos negócios que crescem exponencialmente.",
    template: "Aspecto oculto revelado",
    pain_point: "Dificuldade em escalar o negócio e falta de inovação",
    emotional_trigger: "Ambição / Curiosidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Seu atendimento ao cliente é um gargalo?",
    template: "Diagnóstico do problema",
    pain_point: "Sobrecarga da equipe e clientes insatisfeitos",
    emotional_trigger: "Empatia / Desejo de Excelência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Automação",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Liberte sua equipe para o que realmente importa.",
    template: "Visão transformada + Benefício",
    pain_point: "Equipe sobrecarregada com tarefas operacionais",
    emotional_trigger: "Alívio / Valorização Humana",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Não seja o último a adotar a IA.",
    template: "Urgência + FOMO",
    pain_point: "Medo de obsolescência e perda de competitividade",
    emotional_trigger: "Urgência / Pressão Social",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Automação inteligente: Trabalhe menos, produza mais.",
    template: "Promessa de vida melhor",
    pain_point: "Excesso de trabalho e baixa produtividade",
    emotional_trigger: "Desejo de Liberdade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Automação",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Decisões mais rápidas e precisas?",
    template: "Pergunta + Solução com dados",
    pain_point: "Dificuldade em tomar decisões e falta de dados",
    emotional_trigger: "Confiança / Controle",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Chega de erros humanos!",
    template: "Frustração + Solução automática",
    pain_point: "Erros custosos, retrabalho e perda de credibilidade",
    emotional_trigger: "Segurança / Perfeccionismo",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "O futuro do trabalho é agora: Agentes de IA.",
    template: "Tendência presente + Aplicação prática",
    pain_point: "Rotinas ineficientes e processos engessados",
    emotional_trigger: "Curiosidade / Modernização",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sua empresa está pronta para a revolução?",
    template: "Desafio + Autorreflexão",
    pain_point: "Incerteza sobre a prontidão tecnológica",
    emotional_trigger: "Desafio / Oportunidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "STORY",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Pare de apagar incêndios!",
    template: "Metáfora + Prevenção",
    pain_point: "Reatividade constante e falta de planejamento",
    emotional_trigger: "Alívio / Proatividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Otimize seus gastos com a IA.",
    template: "Economia + Inteligência",
    pain_point: "Desperdício de recursos e orçamentos apertados",
    emotional_trigger: "Inteligência Financeira",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Vendas estagnadas?",
    template: "Pergunta provocadora",
    pain_point: "Dificuldade em identificar novas oportunidades",
    emotional_trigger: "Ambição / Superação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Personalização em massa.",
    template: "Paradoxo resolvido",
    pain_point: "Marketing genérico e baixa taxa de conversão",
    emotional_trigger: "Exclusividade / Conexão",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Segurança de dados e IA.",
    template: "Tranquilidade + Proteção",
    pain_point: "Medo de ataques cibernéticos e perda de dados",
    emotional_trigger: "Segurança / Tranquilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Contrate com inteligência.",
    template: "Triagem inteligente + Fit",
    pain_point: "Dificuldade em encontrar talentos e alta rotatividade",
    emotional_trigger: "Eficiência / Crescimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Inovação sem limites.",
    template: "Possibilidades abertas",
    pain_point: "Falta de inspiração e estagnação criativa",
    emotional_trigger: "Criatividade / Liderança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Perdendo dinheiro para a burocracia?",
    template: "Custo visível + Solução",
    pain_point: "Processos internos lentos e aprovações demoradas",
    emotional_trigger: "Alívio / Descomplicação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Automação",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Cadeia de suprimentos otimizada.",
    template: "Visão transformada + Controle",
    pain_point: "Problemas de estoque e atrasos na logística",
    emotional_trigger: "Controle / Previsibilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Transforme dados em decisões.",
    template: "Alquimia + Poder",
    pain_point: "Excesso de dados brutos sem análise útil",
    emotional_trigger: "Clareza / Vantagem Competitiva",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Perdendo clientes para a concorrência?",
    template: "Ameaça + Proteção",
    pain_point: "Perda de clientes (churn) e baixa retenção",
    emotional_trigger: "Medo de Perder / Lealdade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Maximize seu ROI com a IA.",
    template: "Rendimento máximo",
    pain_point: "Investimentos sem retorno claro",
    emotional_trigger: "Lucratividade / Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Otimize sua produção.",
    template: "Perfeição + Eficiência",
    pain_point: "Gargalos na linha de produção e desperdício",
    emotional_trigger: "Perfeição / Reputação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Equipe de marketing sobrecarregada?",
    template: "Libertação estratégica",
    pain_point: "Excesso de tarefas operacionais no marketing",
    emotional_trigger: "Foco Estratégico",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Deixe a IA fazer o trabalho pesado.",
    template: "Delegação inteligente",
    pain_point: "Tédio com tarefas monótonas",
    emotional_trigger: "Liberdade / Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA como seu consultor estratégico.",
    template: "Acesso ao conhecimento especializado",
    pain_point: "Custos elevados com consultoria externa",
    emotional_trigger: "Acesso ao Conhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Reduza custos operacionais.",
    template: "Economia sustentável",
    pain_point: "Baixa margem de lucro",
    emotional_trigger: "Sustentabilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de projetos com IA.",
    template: "Organização perfeita",
    pain_point: "Atrasos e estouro de orçamento",
    emotional_trigger: "Organização / Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sua empresa preparada para o futuro.",
    template: "Pioneirismo assegurado",
    pain_point: "Medo de ficar obsoleto",
    emotional_trigger: "Pioneirismo",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "STORY",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Aumente a satisfação dos colaboradores.",
    template: "Ambiente de trabalho transformado",
    pain_point: "Baixa moral e alta rotatividade",
    emotional_trigger: "Bem-estar / Engajamento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Desvende o comportamento do consumidor.",
    template: "Poder de conhecer",
    pain_point: "Dificuldade em entender o público-alvo",
    emotional_trigger: "Poder / Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Infraestrutura de TI moderna.",
    template: "Segurança + Velocidade",
    pain_point: "Sistemas lentos e falhas de segurança",
    emotional_trigger: "Segurança / Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Experiências memoráveis para clientes.",
    template: "Encantamento garantido",
    pain_point: "Clientes insatisfeitos e baixa fidelidade",
    emotional_trigger: "Encantamento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA: Sua vantagem competitiva secreta.",
    template: "Segredo revelado",
    pain_point: "Perda de mercado para rivais mais ágeis",
    emotional_trigger: "Vitória / Liderança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Automatize tarefas chatas.",
    template: "Libertação do tédio",
    pain_point: "Perda de tempo com burocracia",
    emotional_trigger: "Realização",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Automação",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão financeira com IA.",
    template: "Domínio total das finanças",
    pain_point: "Orçamentos desorganizados e falta de visão",
    emotional_trigger: "Tranquilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA na saúde (Vertical de impacto).",
    template: "Salvação através da tecnologia",
    pain_point: "Diagnósticos lentos e tratamentos ineficazes",
    emotional_trigger: "Esperança / Cuidado",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Atendimento como diferencial.",
    template: "Exceção nos detalhes",
    pain_point: "Suporte genérico e demorado",
    emotional_trigger: "Excelência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Estoque inteligente.",
    template: "Lucro otimizado",
    pain_point: "Ruptura de estoque ou excesso de produtos",
    emotional_trigger: "Lucratividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA no setor jurídico.",
    template: "Justiça acelerada",
    pain_point: "Análise de documentos demorada e erros",
    emotional_trigger: "Justiça / Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Desbloqueie o potencial da equipe.",
    template: "Evolução contínua",
    pain_point: "Treinamentos genéricos e ineficazes",
    emotional_trigger: "Valorização",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA na educação.",
    template: "Aprendizado personalizado",
    pain_point: "Métodos de ensino padronizados",
    emotional_trigger: "Progresso / Futuro",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de frotas com IA.",
    template: "Controle total",
    pain_point: "Altos custos de combustível e manutenção",
    emotional_trigger: "Segurança / Controle",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Onde estão as oportunidades de mercado?",
    template: "Descoberta guiada",
    pain_point: "Dificuldade em identificar novas tendências",
    emotional_trigger: "Descoberta / Inovação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Automação de marketing inteligente.",
    template: "Reconhecimento imediato",
    pain_point: "Campanhas ineficazes e baixo engajamento",
    emotional_trigger: "Reconhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA na agricultura.",
    template: "Abundância garantida",
    pain_point: "Baixa produtividade e desperdício",
    emotional_trigger: "Abundância",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Proteja-se contra fraudes.",
    template: "Proteção ativa",
    pain_point: "Perdas financeiras por atividades suspeitas",
    emotional_trigger: "Proteção",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "RH estratégico com IA.",
    template: "Crescimento organizacional",
    pain_point: "Processos de seleção lentos",
    emotional_trigger: "Crescimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA no varejo físico e digital.",
    template: "Sem costura entre canais",
    pain_point: "Dificuldade em integrar canais de venda",
    emotional_trigger: "Conveniência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "SaaS",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Pronto para a era dos agentes de IA?",
    template: "Preparação para o futuro",
    pain_point: "Medo do futuro e das mudanças",
    emotional_trigger: "Preparação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "IA",
    content_type: "Reel",
    visual_mode: "Clean",
  },

  // VERTICAL 2: DESENVOLVIMENTO DE SOFTWARE, SISTEMAS E E-COMMERCE (50 hooks)
  {
    text: "Seu site não vende?",
    template: "Diagnóstico + Solução",
    pain_point: "Baixas vendas e experiência ruim",
    emotional_trigger: "Frustração / Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Chega de sistemas engessados!",
    template: "Libertação digital",
    pain_point: "Ineficiência e sistemas que não se adaptam",
    emotional_trigger: "Controle / Otimização",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "E-commerce pronto para o futuro?",
    template: "Escalabilidade garantida",
    pain_point: "Medo de ficar para trás e escala difícil",
    emotional_trigger: "Ambição / Urgência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Transforme sua ideia em realidade.",
    template: "Jornada do projeto",
    pain_point: "Dificuldade em tirar projetos do papel",
    emotional_trigger: "Realização / Confiança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "STORY",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Checkout complicado mata vendas.",
    template: "UX + Conversão",
    pain_point: "Abandono de carrinho e perda de lucro",
    emotional_trigger: "Facilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Seu sistema de gestão é um pesadelo?",
    template: "Transformação operacional",
    pain_point: "Desorganização e estresse operacional",
    emotional_trigger: "Alívio / Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "E-commerce que vende 24h.",
    template: "Automação de vendas",
    pain_point: "Dependência de vendas físicas/horário",
    emotional_trigger: "Liberdade / Expansão",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Por onde começar seu sistema?",
    template: "Guia estratégico",
    pain_point: "Incerteza e falta de conhecimento técnico",
    emotional_trigger: "Segurança / Clareza",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "LIST",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sistemas inteligentes = Menos esforço.",
    template: "Automação + Inteligência",
    pain_point: "Erros manuais e processos lentos",
    emotional_trigger: "Inteligência / Progresso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Seu e-commerce é seguro?",
    template: "Checklist de segurança",
    pain_point: "Medo de ataques e perda de reputação",
    emotional_trigger: "Segurança / Confiança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Transforme dados em lucro (BI).",
    template: "Business Intelligence",
    pain_point: "Decisões baseadas em intuição",
    emotional_trigger: "Vantagem Competitiva",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Seu app dos sonhos em iOS e Android.",
    template: "Presença mobile",
    pain_point: "Falta de presença mobile",
    emotional_trigger: "Modernidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "E-commerce B2B simplificado.",
    template: "Portal corporativo",
    pain_point: "Processos corporativos complexos",
    emotional_trigger: "Profissionalismo",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Modernize seu legado (Cloud).",
    template: "Migração para nuvem",
    pain_point: "Sistemas antigos lentos e caros",
    emotional_trigger: "Alívio / Modernidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "MVP de sucesso para sua startup.",
    template: "Validação rápida",
    pain_point: "Medo de falhar e alto custo inicial",
    emotional_trigger: "Agilidade / Oportunidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "STORY",
    niche: "Startups",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de estoque sem perdas.",
    template: "Controle automatizado",
    pain_point: "Ruptura de estoque e prejuízo",
    emotional_trigger: "Lucratividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Portal exclusivo para clientes.",
    template: "Autoatendimento + Fidelidade",
    pain_point: "Baixa fidelidade e suporte ruim",
    emotional_trigger: "Exclusividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Automação de processos internos.",
    template: "Fluxo transformado",
    pain_point: "Desperdício de tempo e recursos",
    emotional_trigger: "Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Mais tráfego para seu e-commerce.",
    template: "SEO técnico",
    pain_point: "Baixa visibilidade no Google",
    emotional_trigger: "Crescimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "APIs personalizadas: Integre tudo.",
    template: "Conectividade total",
    pain_point: "Sistemas isolados que não conversam",
    emotional_trigger: "Conectividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "UX impecável retém clientes.",
    template: "Design centrado no usuário",
    pain_point: "Clientes frustrados com navegação",
    emotional_trigger: "Excelência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "CRM personalizado vs. Planilhas.",
    template: "Organização de dados",
    pain_point: "Desorganização de dados de clientes",
    emotional_trigger: "Controle",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "App que realmente engaja.",
    template: "Retenção + Engagement",
    pain_point: "Aplicativos pouco utilizados",
    emotional_trigger: "Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de projetos sem estresse.",
    template: "Organização perfeita",
    pain_point: "Atrasos e falta de comunicação",
    emotional_trigger: "Organização / Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Estabilidade em picos de venda.",
    template: "Infraestrutura escalável",
    pain_point: "Quedas do site na Black Friday",
    emotional_trigger: "Segurança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Plataformas educacionais (EAD).",
    template: "Educação online",
    pain_point: "Alcance limitado de cursos presenciais",
    emotional_trigger: "Impacto / Reconhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Produtividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Automação de vendas para o time.",
    template: "Funil otimizado",
    pain_point: "Time comercial focado em burocracia",
    emotional_trigger: "Lucratividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sistemas modulares e flexíveis.",
    template: "Escalabilidade contínua",
    pain_point: "Dificuldade em evoluir o software",
    emotional_trigger: "Praticidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Diferencial competitivo no e-commerce.",
    template: "Inovação + Funcionalidades únicas",
    pain_point: "Concorrência vendendo a mesma coisa",
    emotional_trigger: "Inovação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão financeira total.",
    template: "Controle de fluxo de caixa",
    pain_point: "Falta de visibilidade do fluxo de caixa",
    emotional_trigger: "Tranquilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Velocidade é dinheiro no e-commerce.",
    template: "Performance + Conversão",
    pain_point: "Clientes abandonam sites lentos",
    emotional_trigger: "Urgência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Crie um Marketplace de sucesso.",
    template: "Gerenciamento multiseller",
    pain_point: "Gestão complexa de vários vendedores",
    emotional_trigger: "Liderança de Mercado",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Seu site não é responsivo?",
    template: "Mobile First",
    pain_point: "Perda de clientes no mobile",
    emotional_trigger: "Modernidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Agendamento online automático.",
    template: "Conveniência total",
    pain_point: "Perda de tempo marcando horários",
    emotional_trigger: "Conveniência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Realidade Aumentada no E-commerce.",
    template: "Visualização 3D",
    pain_point: "Dificuldade em visualizar o produto",
    emotional_trigger: "Encantamento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Intranet para comunicação interna.",
    template: "Centralização de conhecimento",
    pain_point: "Equipes desinformadas e isoladas",
    emotional_trigger: "Pertencimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "CMS: Controle total do seu site.",
    template: "Autonomia total",
    pain_point: "Dependência de programador",
    emotional_trigger: "Autonomia",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Apareça no topo do Google.",
    template: "Estratégia SEO",
    pain_point: "Baixo tráfego orgânico",
    emotional_trigger: "Reconhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gamificação para engajamento.",
    template: "Motivação + Recompensa",
    pain_point: "Falta de motivação de clientes/equipe",
    emotional_trigger: "Recompensa",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de documentos (GED).",
    template: "Digitalização inteligente",
    pain_point: "Papelada física e perda de arquivos",
    emotional_trigger: "Segurança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Aplicativo interno para sua equipe.",
    template: "Controle de campo",
    pain_point: "Dificuldade em gerenciar pessoal de campo",
    emotional_trigger: "Controle",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "E-commerce com IA integrada.",
    template: "Recomendação personalizada",
    pain_point: "Recomendações de produtos genéricas",
    emotional_trigger: "Exclusividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "CRM para fidelização extrema.",
    template: "Lealdade contínua",
    pain_point: "Falta de histórico de interações",
    emotional_trigger: "Lealdade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Mobile-First como prioridade.",
    template: "Otimização mobile",
    pain_point: "Sites que não funcionam bem no 4G/5G",
    emotional_trigger: "Modernidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de assinaturas (Recorrência).",
    template: "Receita previsível",
    pain_point: "Receita instável mês a mês",
    emotional_trigger: "Previsibilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "E-learning personalizado.",
    template: "Treinamento contínuo",
    pain_point: "Treinamentos de funcionários ineficazes",
    emotional_trigger: "Crescimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Produtividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sistema de vendas ultrarrápido.",
    template: "Compra com um clique",
    pain_point: "Processo de checkout demorado",
    emotional_trigger: "Agilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Pagamentos flexíveis (Pix/Cartão).",
    template: "Múltiplas opções",
    pain_point: "Perda de venda por falta de opção",
    emotional_trigger: "Satisfação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão de eventos e inscrições.",
    template: "Automação de eventos",
    pain_point: "Processos manuais em eventos",
    emotional_trigger: "Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Blog integrado ao E-commerce.",
    template: "Autoridade + Vendas",
    pain_point: "Falta de autoridade e conteúdo",
    emotional_trigger: "Autoridade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Tech",
    content_type: "Reel",
    visual_mode: "Clean",
  },

  // VERTICAL 3: STUDIO CRIATIVO COM IA (50 hooks)
  {
    text: "Sua campanha está invisível?",
    template: "Visibilidade + Impacto",
    pain_point: "Baixo engajamento e falta de impacto",
    emotional_trigger: "Reconhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Chega de publicidade genérica.",
    template: "Autenticidade garantida",
    pain_point: "Falta de conexão emocional com o público",
    emotional_trigger: "Autenticidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "O futuro da publicidade é agora.",
    template: "IA transformando criativos",
    pain_point: "Campanhas caras e ineficazes",
    emotional_trigger: "Visão de Futuro",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sua marca merece uma história épica.",
    template: "Storytelling visual",
    pain_point: "Dificuldade em contar a história da marca",
    emotional_trigger: "Inspiração",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Fim dos brainstormings infinitos.",
    template: "Geração rápida de conceitos",
    pain_point: "Bloqueio criativo e reuniões lentas",
    emotional_trigger: "Agilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Personalização em escala (Criativos).",
    template: "Variações únicas",
    pain_point: "Criativos únicos para cada segmento",
    emotional_trigger: "Conexão",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Orçamento de marketing limitado?",
    template: "Economia de produção",
    pain_point: "Desperdício de recursos em produção cara",
    emotional_trigger: "Inteligência Financeira",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Anúncios que ninguém ignora.",
    template: "Psicologia visual",
    pain_point: "Baixa atenção nas redes sociais",
    emotional_trigger: "Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Inove ou morra (Agências).",
    template: "Transformação digital",
    pain_point: "Estagnação e perda de mercado",
    emotional_trigger: "Urgência / Liderança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Dados transformados em arte.",
    template: "Inteligência + Criatividade",
    pain_point: "Campanhas baseadas apenas em feeling",
    emotional_trigger: "Clareza",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Produção de vídeo ultrarrápida.",
    template: "Criação acelerada",
    pain_point: "Prazos apertados e custos de edição",
    emotional_trigger: "Modernidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Criativos para cada plataforma.",
    template: "Adaptação automática",
    pain_point: "Retrabalho para adaptar formatos",
    emotional_trigger: "Versatilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Uma voz única para sua marca.",
    template: "Identidade verbal",
    pain_point: "Identidade verbal fraca e genérica",
    emotional_trigger: "Originalidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Campanhas que leem a mente.",
    template: "Previsão + Relevância",
    pain_point: "Baixa conversão e mensagens irrelevantes",
    emotional_trigger: "Surpresa / Conexão",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Edição de vídeo em minutos.",
    template: "Pós-produção automática",
    pain_point: "Custos e tempo de pós-produção",
    emotional_trigger: "Produtividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Personagens e cenários incríveis.",
    template: "Mundos virtuais",
    pain_point: "Limitações físicas de locação e atores",
    emotional_trigger: "Fantasia / Inovação",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Publicidade que gera leads.",
    template: "Beleza + Vendas",
    pain_point: "Campanhas que são bonitas mas não vendem",
    emotional_trigger: "Lucratividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Qualidade de cinema para PMEs.",
    template: "Produção escalada",
    pain_point: "Custos proibitivos de grandes produções",
    emotional_trigger: "Ambição / Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Saiba o que seu público quer ver.",
    template: "Análise de tendências",
    pain_point: "Conteúdo que não gera engajamento",
    emotional_trigger: "Controle",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Campanhas virais via IA.",
    template: "Gatilhos de compartilhamento",
    pain_point: "Dificuldade em ser compartilhado",
    emotional_trigger: "Popularidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Jingles inesquecíveis.",
    template: "Identidade sonora",
    pain_point: "Falta de identidade sonora",
    emotional_trigger: "Emoção",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Estratégia de mídia inteligente.",
    template: "Alocação de investimento",
    pain_point: "Investimento em canais errados",
    emotional_trigger: "Precisão",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Anúncios em vídeo que convertem.",
    template: "VSL + Performance",
    pain_point: "Falta de expertise em roteiro de vendas",
    emotional_trigger: "Profissionalismo",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Sua marca sempre atualizada.",
    template: "Modernidade visual",
    pain_point: "Campanhas com visual datado",
    emotional_trigger: "Relevância",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Automação de design (Social Media).",
    template: "Geração contínua",
    pain_point: "Sobrecarga de criação de peças diárias",
    emotional_trigger: "Liberdade Criativa",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "SWAP",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "IA como seu Diretor de Arte.",
    template: "Conceitos visuais",
    pain_point: "Custos de direção de arte sênior",
    emotional_trigger: "Exclusividade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Influenciadores perfeitos (IA).",
    template: "Análise de fit",
    pain_point: "Escolha errada de parceiros de marca",
    emotional_trigger: "Autenticidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Logos memoráveis.",
    template: "Design de marca",
    pain_point: "Identidade visual sem impacto",
    emotional_trigger: "Reconhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Conteúdo que engaja e converte.",
    template: "Otimização total",
    pain_point: "Baixa interação nas redes",
    emotional_trigger: "Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Experiências imersivas (AR/VR).",
    template: "Interatividade 3D",
    pain_point: "Publicidade estática e chata",
    emotional_trigger: "Encantamento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "E-mail Marketing que converte.",
    template: "Personalização de email",
    pain_point: "Baixa taxa de abertura",
    emotional_trigger: "Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Apresentações de impacto.",
    template: "Storytelling em decks",
    pain_point: "Slides chatos que não convencem",
    emotional_trigger: "Desejo de Impressionar",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Comunicação interna engajadora.",
    template: "Vídeos internos",
    pain_point: "Funcionários que não leem comunicados",
    emotional_trigger: "Clareza",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Mascotes de marca únicos.",
    template: "Personagens consistentes",
    pain_point: "Falta de um elemento carismático",
    emotional_trigger: "Carisma",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Anúncios que se destacam no feed.",
    template: "Pattern Interrupt visual",
    pain_point: "Público que passa direto pelo post",
    emotional_trigger: "Visibilidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Tours Virtuais Imersivos.",
    template: "Experiência 360º",
    pain_point: "Dificuldade em mostrar espaços físicos",
    emotional_trigger: "Conveniência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "SEO de conteúdo via IA.",
    template: "Artigos otimizados",
    pain_point: "Textos que não atraem tráfego",
    emotional_trigger: "Reconhecimento",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Vídeos explicativos simples.",
    template: "Animações didáticas",
    pain_point: "Produtos complexos difíceis de vender",
    emotional_trigger: "Clareza",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Slogans que vendem.",
    template: "Taglines poderosas",
    pain_point: "Frases de efeito que ninguém lembra",
    emotional_trigger: "Identidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Eventos e Stands interativos.",
    template: "Experiências on-site",
    pain_point: "Stands sem visitantes em feiras",
    emotional_trigger: "Destaque",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Toque humano na IA (Voz).",
    template: "Narração emocional",
    pain_point: "Vozes robóticas que afastam",
    emotional_trigger: "Autenticidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Campanhas de Impacto Social.",
    template: "Conteúdo com propósito",
    pain_point: "Dificuldade em mobilizar causas",
    emotional_trigger: "Empatia / Propósito",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "STORY",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Gestão estratégica de redes.",
    template: "Calendário de conteúdo",
    pain_point: "Posts sem frequência ou estratégia",
    emotional_trigger: "Eficiência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Identidade Visual 360º.",
    template: "Unificação visual",
    pain_point: "Marca inconsistente em diferentes canais",
    emotional_trigger: "Modernidade",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Viralização em TikTok/Reels.",
    template: "Tendências + Áudios",
    pain_point: "Falta de criatividade para vídeos curtos",
    emotional_trigger: "Sucesso",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CURIOSIDADE",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Publicidade baseada em insights.",
    template: "Big Data + Criatividade",
    pain_point: "Campanhas sem embasamento real",
    emotional_trigger: "Inteligência",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Podcasts e Áudios de marca.",
    template: "Conteúdo sonoro",
    pain_point: "Dificuldade em produzir áudio de qualidade",
    emotional_trigger: "Conexão",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Criatividade",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Storytelling que emociona.",
    template: "Jornada do herói",
    pain_point: "Marca fria e sem conexão",
    emotional_trigger: "Inspiração",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "STORY",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Anúncios em Streaming (Netflix/Spotify).",
    template: "Novos canais",
    pain_point: "Dificuldade em entrar em novos canais",
    emotional_trigger: "Alcance",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "BUILD",
    niche: "Marketing",
    content_type: "Reel",
    visual_mode: "Clean",
  },
  {
    text: "Adaptando-se à era da IA.",
    template: "Inovação contínua",
    pain_point: "Medo de ser substituído por tecnologia",
    emotional_trigger: "Liderança",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Campanhas",
    content_type: "Reel",
    visual_mode: "Clean",
  },
];

export async function seed150HooksComplete(workspaceId: string) {
  try {
    // Get current user ID (required by RLS)
    const { data } = await supabase.auth.getUser();
    const userId = data?.user?.id;

    if (!userId) throw new Error("User not authenticated");

    // Delete existing hooks
    const { error: deleteError } = await supabase
      .from("hooks")
      .delete()
      .eq("workspace_id", workspaceId);

    if (deleteError) throw deleteError;

    // Insert new hooks in batches (like seedHooksToDatabase does)
    const batchSize = 5;
    let totalInserted = 0;

    for (let i = 0; i < hooks150Complete.length; i += batchSize) {
      const batch = hooks150Complete.slice(i, i + batchSize);
      const { data: inserted, error: insertError } = await supabase
        .from("hooks")
        .insert(
          batch.map((hook) => ({
            workspace_id: workspaceId,
            created_by: userId,
            text: hook.text,
            template: hook.template,
            pain_point: hook.pain_point,
            emotional_trigger: hook.emotional_trigger,
            creator: hook.creator,
            creator_handle: hook.creator_handle,
            type: hook.type,
            niche: hook.niche,
            content_type: hook.content_type || "Reel",
            visual_mode: hook.visual_mode || "Clean",
            views: Math.floor(Math.random() * 8000) + 1000,
            times_used: Math.floor(Math.random() * 25),
          }))
        )
        .select();

      if (insertError) {
        console.error(`❌ Erro no batch ${Math.floor(i / batchSize) + 1}:`, insertError);
        throw insertError;
      }

      const batchCount = inserted?.length || 0;
      totalInserted += batchCount;
    }

    return {
      success: true,
      count: totalInserted,
      message: `150 hooks foram importados com sucesso! ✅`,
    };
  } catch (error) {
    console.error("Erro ao fazer seed dos 150 hooks:", error);
    throw error;
  }
}
