import { supabase } from "@/integrations/supabase/client";
import type { CreateHookInput } from "@/types/hooks";
import { hookMetadata } from "./hookMetadata";

// 50 Hooks Estruturados - Dores + Métricas para PMEs
// Fonte: Documento de Posicionamento de Conteúdo
export const seedHooks: CreateHookInput[] = [
  // === SISTEMA 1: DORES / TEMAS CENTRAIS (01-25) ===
  {
    text: "O Funcionário Robô: Você está pagando salário sênior para alguém apertar botões?",
    template: "Você está pagando salário sênior para [FUNÇÃO] apertar botões repetitivos?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Clean",
    views: 450000,
  },
  {
    text: "A Dependência Vital: Se seu dono não olhar WhatsApp por 2 horas, o negócio para de faturar.",
    template: "Se o dono não olhar [CANAL] por 2 horas, a operação [PARA/ESFRIA].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Story",
    visualMode: "Clean",
    views: 520000,
  },
  {
    text: "O Conhecimento Centralizado: Todo processo da empresa na cabeça de uma pessoa = risco crítico.",
    template: "Quando [PROCESSO] depende só de [PESSOA], você está em risco crítico.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Produtividade",
    contentType: "Post",
    visualMode: "Dark",
    views: 390000,
  },
  {
    text: "A Caça ao Tesouro: Seu time perde 40 minutos procurando um arquivo ou contrato.",
    template: "Quantas horas seu time perde procurando [DOCUMENTO] que 'alguém salvou em algum lugar'?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Reel",
    visualMode: "Clean",
    views: 480000,
  },
  {
    text: "O Medo do Sucesso: Fechar 10 clientes novos e a operação quebrar por falta de braço.",
    template: "Você tem medo de crescer porque sabe que [SISTEMA] não aguenta [VOLUME].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 410000,
  },
  {
    text: "O Comercial Tartaruga: Lead quente esfria e compra do concorrente por demora na resposta.",
    template: "Quantos leads você perde porque o time demora [TEMPO] para responder?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Marketing",
    contentType: "Post",
    visualMode: "Clean",
    views: 540000,
  },
  {
    text: "Contratação Errada como Remédio: Trazer mais gente para um processo quebrado na base.",
    template: "Antes de contratar, pergunte: o [PROCESSO] está quebrado ou só precisa ser automatizado?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Produtividade",
    contentType: "Carrossel",
    visualMode: "Clean",
    views: 470000,
  },
  {
    text: "A Síndrome da Reunião Infinita: 2 horas de alinhamento que poderiam ser um dashboard.",
    template: "[REUNIÃO] de [TEMPO] que poderia ser [MÉTRICA] automática num dashboard.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Produtividade",
    contentType: "Reel",
    visualMode: "Dark",
    views: 510000,
  },
  {
    text: "A Síndrome do Babá: O desgaste de cobrar o time o tempo todo para saber se a tarefa foi feita.",
    template: "Quantas vezes você cobra o mesmo status que poderia estar [AUTOMÁTICO]?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Story",
    visualMode: "Clean",
    views: 430000,
  },
  {
    text: "O Ralo de Dinheiro Oculto: Lucro escorrendo entre ferramentas caras nunca usadas.",
    template: "Quanto você paga em softwares que [NINGUÉM USA]?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Post",
    visualMode: "Dark",
    views: 460000,
  },
  {
    text: "O Frankenstein Digital: 10 ferramentas desconectadas dependendo de 'copiar e colar'.",
    template: "Sua operação é um [FRANKENSTEIN]: [FERRAMENTA1] → copiar → [FERRAMENTA2] → copiar → [FERRAMENTA3].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 495000,
  },
  {
    text: "O Retrabalho Caro: Errar CPF de cliente no contrato por digitação manual custa lucro.",
    template: "Quantas vezes você ou o cliente encontrou [ERRO SIMPLES] que poderia ter sido validado?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Clean",
    views: 440000,
  },
  {
    text: "A Inércia do 'Sempre foi assim': Empresas tradicionais sendo engolidas por novatas com IA.",
    template: "Seu concorrente novo está usando [AUTOMAÇÃO] enquanto você faz [MANUALMENTE].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "IA",
    contentType: "Reel",
    visualMode: "Dark",
    views: 570000,
  },
  {
    text: "O Apagador de Incêndios: Acorda para planejar o futuro, passa o dia em urgências.",
    template: "Quantas estratégias você deixou de lado porque estava apagando incêndio?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Produtividade",
    contentType: "Story",
    visualMode: "Clean",
    views: 485000,
  },
  {
    text: "O Paradoxo do Crescimento: Faturamento sobe, lucro cai por ineficiência de escala.",
    template: "Sua receita [CRESCE] mas o lucro [CAI]. O problema é a ineficiência, não a demanda.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 520000,
  },
  {
    text: "O Fator 'E se eu sumir?': Se tirar 30 dias de férias, sua empresa sobrevive?",
    template: "Se você desaparecer por 30 dias, quantos [PROCESSOS] param?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Dark",
    views: 510000,
  },
  {
    text: "O Cliente Ditador: Clientes exigem escopo extra porque não há trava de processo.",
    template: "Seus clientes exploram porque faltam validações automáticas no [PROCESSO].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Reel",
    visualMode: "Clean",
    views: 465000,
  },
  {
    text: "A Notificação Fantasma: Checando Slack às 22h de domingo por ansiedade.",
    template: "Quando você para de checkar [CANAL], quantas coisas importantes foram perdidas?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Produtividade",
    contentType: "Story",
    visualMode: "Dark",
    views: 475000,
  },
  {
    text: "O 'Paguei e não vi': O ranço de contratar consultorias que só entregam PDFs teóricos.",
    template: "Consultoria entregou [PDF BONITO] mas sua operação continua [CAÓTICA].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Clean",
    views: 490000,
  },
  {
    text: "A Síndrome do Impostor do Dono: Sentir que a empresa é uma fachada prestes a desabar.",
    template: "Você sente que a empresa é frágil demais, dependente de [PESSOAS], sem [PROCESSOS]?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Post",
    visualMode: "Dark",
    views: 505000,
  },
  {
    text: "O Turnover Silencioso: Talentos bons pedem demissão porque não aguentam o caos.",
    template: "Seus melhores foram embora porque [OPERAÇÃO] é caótica, não por salary.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Produtividade",
    contentType: "Reel",
    visualMode: "Clean",
    views: 440000,
  },
  {
    text: "A Proposta no Limbo: Propostas enviadas que nunca recebem follow-up por esquecimento.",
    template: "Quantas propostas você enviou e esqueceu de dar follow-up?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Marketing",
    contentType: "Story",
    visualMode: "Clean",
    views: 455000,
  },
  {
    text: "O Blecaute Operacional: Quando o gestor de projetos fica doente, ninguém sabe fazer nada.",
    template: "Se [PESSOA CHAVE] não puder trabalhar amanhã, [PROCESSO] para?",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Dark",
    views: 495000,
  },
  {
    text: "O Overdelivering Invisível: Entregar o dobro e queimar margem de lucro sem perceber.",
    template: "Você entrega [ESCOPO_EXTRA] sem cobrar, e a margem [DESAPARECE].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Clean",
    views: 470000,
  },
  {
    text: "O Orgulho do 'Deixa que eu faço': O ego que centraliza tudo, disfarçado de qualidade.",
    template: "Você centraliza [PROCESSO] por 'garantir qualidade', mas na real está frenando a empresa.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Produtividade",
    contentType: "Reel",
    visualMode: "Dark",
    views: 515000,
  },

  // === SISTEMA 2: MÉTRICAS / TEMAS ANALÍTICOS (26-50) ===
  {
    text: "A Matemática do Desperdício: Quanto custa 20 horas semanais de digitação manual?",
    template: "20h/semana × R$ [CUSTO_HORA] × 52 semanas = R$ [DESPERDÍCIO] ao ano em [AÇÃO].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Clean",
    views: 520000,
  },
  {
    text: "Checklist de Margem de Erro: Reduzir falha humana a zero com validações automáticas.",
    template: "Taxa de erro manual: [PERCENTUAL]% | Taxa de erro automático: 0% | ROI: [VALOR].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Clean",
    views: 450000,
  },
  {
    text: "Custo de Oportunidade: Enquanto seu vendedor preenche CRM, deixa de fechar R$ XXXX.",
    template: "Seu vendedor perde [TEMPO] preenchendo CRM = [LEADS] não fechados = R$ [PREJUÍZO].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Marketing",
    contentType: "Reel",
    visualMode: "Dark",
    views: 490000,
  },
  {
    text: "O Gargalo do Relógio: Auditoria de tempo - para onde vão as horas da liderança?",
    template: "Seu CEO gasta [PERCENTUAL]% do tempo em [TAREFAS_OPERACIONAIS] ao invés de [ESTRATÉGIA].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Produtividade",
    contentType: "Story",
    visualMode: "Clean",
    views: 470000,
  },
  {
    text: "Auditoria de Assinaturas: Economize até 40% cortando softwares redundantes.",
    template: "Você paga [VALOR] em [FERRAMENTA1] E [FERRAMENTA2] que fazem a mesma coisa.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 510000,
  },
  {
    text: "A Regra dos Três Cliques: Se demora mais de 3 cliques, deve ser automatizado.",
    template: "Processo [ATUAL]: [CLIQUES] cliques | [PROPOSTO]: 1 clique automático.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Clean",
    views: 460000,
  },
  {
    text: "Investimento vs Headcount: 1 licença de automação vs 3 contratações CLT.",
    template: "R$ [AUTOMAÇÃO]/mês vs R$ [SALÁRIO] × 3 = economia de R$ [TOTAL].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 540000,
  },
  {
    text: "Capacidade Limite (FTE): Triplicar a entrega sem contratar ninguém.",
    template: "Seu time atual pode fazer 3x mais de [ESCOPO] se [PROCESSO] for automático.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Reel",
    visualMode: "Clean",
    views: 485000,
  },
  {
    text: "O Cronômetro do SLA: Responder lead em até 5 min aumenta vendas em 391%.",
    template: "Resposta em 5 min: 391% conversão | Resposta em 1h: [PERCENTUAL]% conversão.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Marketing",
    contentType: "Post",
    visualMode: "Dark",
    views: 520000,
  },
  {
    text: "Escala de MRR sem Caos: A arquitetura técnica necessária para operação previsível.",
    template: "Para faturar R$ [X]/mês com [Y] clientes, você precisa de [AUTOMAÇÕES] implementadas.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 505000,
  },
  {
    text: "Dívida Técnica Operacional: O que é e como cobra juros caros no faturamento.",
    template: "Cada [PROCESSO_MANUAL] é dívida que rende [JUROS] em atraso e retrabalho.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Automação",
    contentType: "Story",
    visualMode: "Dark",
    views: 475000,
  },
  {
    text: "CAC Desbalanceado: Falta de automação pós-venda destrói lucro do marketing.",
    template: "Marketing gasta R$ [CAC] adquirindo, mas pós-venda manual consome R$ [CUSTO].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Marketing",
    contentType: "Reel",
    visualMode: "Clean",
    views: 495000,
  },
  {
    text: "Tempo Médio de Atendimento: Onboarding de 5 dias reduzido para 5 minutos.",
    template: "Onboarding [ATUAL]: 5 dias | Onboarding [AUTOMÁTICO]: 5 minutos.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Clean",
    views: 470000,
  },
  {
    text: "Margem por Linha de Serviço: Identificar e eliminar o serviço menos lucrativo.",
    template: "Serviço [A] consome [TEMPO] = R$ [MARGEM] | Serviço [B] consome [TEMPO] = R$ [MARGEM].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 515000,
  },
  {
    text: "Índice de Retrabalho: Automação erra 0% comparada ao preenchimento humano.",
    template: "Taxa retrabalho humano: [PERCENTUAL]% | Taxa retrabalho automático: 0%.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Clean",
    views: 490000,
  },
  {
    text: "ROI de Automação de Processos: Recuperar 120 horas de trabalho em 30 dias.",
    template: "Projeto automação: [INVESTIMENTO] → Retorno: 120h em 30 dias = ROI [PERCENTUAL]%.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Automação",
    contentType: "Reel",
    visualMode: "Dark",
    views: 530000,
  },
  {
    text: "Time-to-Value (TTV): Encantar cliente nas primeiras 24h com entregas automáticas.",
    template: "Cliente entrega acesso em 24h via automação = satisfação [PERCENTUAL]% maior.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Story",
    visualMode: "Clean",
    views: 465000,
  },
  {
    text: "Gargalo de Aprovação Interna: Eliminar atrasos com alertas automáticos.",
    template: "Quando aprovação atrasa, alerta automático + escalação = [TEMPO_REDUZIDO].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Clean",
    views: 480000,
  },
  {
    text: "Custo por Lead Qualificado (SQL): IA qualifica leads antes do comercial.",
    template: "IA qualifica e segmenta [NÚMERO] leads automático = Comercial fecha [PERCENTUAL]% mais.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "IA",
    contentType: "Post",
    visualMode: "Dark",
    views: 505000,
  },
  {
    text: "Repositório Vivo de Processos: Processos executáveis ao invés de PDFs.",
    template: "Manual em PDF: ninguém lê | Processo automático: roda sozinho 100% correto.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Reel",
    visualMode: "Clean",
    views: 475000,
  },
  {
    text: "Produtividade por FTE: A engenharia por trás de operações que faturam milhões.",
    template: "[EMPRESA] faturas R$ [X]M com [Y] pessoas = R$ [PRO_FTE] por FTE.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "PME",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 510000,
  },
  {
    text: "Taxa de Conversão por Etapa: Monitorando a saúde do funil operacional.",
    template: "Etapa 1: [%] | Etapa 2: [%] | Etapa 3: [%] = Gargalo em [ETAPA].",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Story",
    visualMode: "Clean",
    views: 495000,
  },
  {
    text: "Variabilidade de Entrega: O perigo de entregar escopos diferentes mesmo preço.",
    template: "Cliente 1: [ESCOPO_REAL] | Cliente 2: [ESCOPO_REAL] = Margem completamente diferente.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Automação",
    contentType: "Post",
    visualMode: "Dark",
    views: 520000,
  },
  {
    text: "Lifetime Value (LTV) Otimizado: Processos cirúrgicos retêm clientes por mais tempo.",
    template: "LTV com processos manual: [VALOR] | LTV com automação: [VALOR] = +[PERCENTUAL]%.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CLAIM",
    niche: "Automação",
    contentType: "Carrossel",
    visualMode: "Dark",
    views: 535000,
  },
  {
    text: "Alocação Estratégica do Dono: As horas que separam o Dono Operador do CEO.",
    template: "Dono operador: [HORAS]% em operação | CEO: [HORAS]% em estratégia + [HORAS]% delegado.",
    creator: "Koraflow",
    creator_handle: "@koraflow",
    type: "CONTRARIAN",
    niche: "Produtividade",
    contentType: "Reel",
    visualMode: "Dark",
    views: 505000,
  },
];

export async function seedHooksToDatabase(workspaceId: string) {
  try {
    const { data } = await supabase.auth.getUser();
    const userId = data?.user?.id;

    if (!userId) throw new Error("User not authenticated");

    console.log("🌱 Iniciando seed de hooks...");
    console.log(`   Total de hooks para inserir: ${seedHooks.length}`);

    // Delete existing hooks first to avoid duplicates
    const { error: deleteError } = await supabase
      .from("hooks")
      .delete()
      .eq("workspace_id", workspaceId);

    if (deleteError) {
      console.warn("⚠️ Erro ao deletar hooks antigos:", deleteError);
    } else {
      console.log("✅ Hooks antigos deletados");
    }

    // Insert all hooks in smaller batches
    const batchSize = 5;
    let totalInserted = 0;

    for (let i = 0; i < seedHooks.length; i += batchSize) {
      const batch = seedHooks.slice(i, i + batchSize);
      const { data: inserted, error: insertError } = await supabase
        .from("hooks")
        .insert(
          batch.map((hook, batchIndex) => {
            const hookIndex = i + batchIndex;
            const metadata = hookMetadata[hookIndex] || {};
            return {
              workspace_id: workspaceId,
              created_by: userId,
              text: hook.text,
              template: hook.template,
              creator: hook.creator,
              creator_handle: hook.creator_handle,
              type: hook.type,
              niche: hook.niche,
              views: hook.views || 0,
              content_type: hook.contentType || "Reel",
              visual_mode: hook.visualMode || "Dark",
              theme: hook.theme,
              emotional_trigger: metadata.emotionalTrigger,
              pain_point: metadata.painPoint,
              // system_type será preenchido na próxima iteração
            };
          })
        )
        .select();

      if (insertError) {
        console.error(`❌ Erro no batch ${Math.floor(i / batchSize) + 1}:`, insertError);
        throw insertError;
      }

      const batchCount = inserted?.length || 0;
      totalInserted += batchCount;
      console.log(`✅ Batch ${Math.floor(i / batchSize) + 1}: ${batchCount} hooks inseridos (total: ${totalInserted})`);
    }

    console.log(`🎉 Seed concluído! Total: ${totalInserted} hooks`);
    return { success: true, count: totalInserted, message: `${totalInserted} hooks importados com sucesso!` };
  } catch (error) {
    console.error("Error seeding hooks:", error);
    throw error;
  }
}
