// Gerado automaticamente a partir de public/playbook-full.html (extração verificada byte-a-byte).
// Conteúdo comercial do Playbook — editar aqui edita o que aparece no modal de cada plano.

export interface PlaybookPlan {
  id: string;
  badge: string;
  badgeStyle: string;
  name: string;
  sub: string;
  tabs: Record<string, string>;
}

export const TAB_ORDER = ["t0","t1","t2","t3","t4","t5","t6"] as const;

export const TAB_LABELS: Record<string, string> = {
  "t0": "Visão Geral",
  "t1": "Preço & Barganha",
  "t2": "Mentalidade",
  "t3": "Scripts",
  "t4": "Fluxo da Call",
  "t5": "Objeções",
  "t6": "vs Alternativas"
};

export const PLAYBOOK_PLANS: Record<string, PlaybookPlan> = {
  "agent-chat": {
    id: "agent-chat",
    badge: "KORA AGENT · ENTRY POINT",
    badgeStyle: "background:rgba(0,229,255,0.08);color:var(--agent);border:1px solid rgba(0,229,255,0.18);",
    name: "KORA CHAT",
    sub: "WhatsApp centralizado · Atendentes humanos · Sem IA",
    tabs: {
      t0: `<div class="ttl2">O que e o Kora Chat?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">WhatsApp da empresa conectado ao Chatwoot white label. Todos os atendentes sao humanos — sem IA. Ideal para organizar o atendimento antes de introduzir automacao.</p><div class="nota nota-green"><span class="nota-i">→</span><span>Porta de entrada: quando o cliente quiser IA, a plataforma ja e a mesma. E so ativar o BASE.</span></div><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--agent)">R$0</div><div class="ic-lbl">Custo de implantacao. Zero setup. Entra hoje.</div></div><div class="ic"><div class="ic-num" style="color:var(--agent)">R$97</div><div class="ic-lbl">Por usuario/mes. Min. 3 usuarios = R$297/mes.</div></div><div class="ic"><div class="ic-num" style="color:var(--agent)">24/7</div><div class="ic-lbl">Visibilidade total do time numa plataforma profissional.</div></div><div class="ic"><div class="ic-num" style="color:var(--agent)">1-click</div><div class="ic-lbl">Upgrade para BASE com agente de IA a qualquer momento.</div></div></div>`,
      t1: `<div class="ttl2" style="margin-bottom:12px">Estrutura de Preco</div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Setup</div><div class="pdg-val">R$ 0</div><div class="pdg-sub">Sem implantacao. Ativacao imediata.</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia</div><div class="pdg-val" style="color:var(--agent)">R$ 97/mes</div><div class="pdg-sub">/usuario/mes · min. 3 usuarios</div><div class="pdg-cond">Min. R$297/mes</div></div></div><div class="ttl2" style="margin-bottom:10px;margin-top:18px">Margem de Barganha</div><div class="pl"><div class="pl-row pl-hdr"><span>Nivel</span><span>Preco</span><span>Piso</span><span>Quando Ceder</span></div><div class="pl-row"><span class="pl-lbl">Ancoragem</span><span class="pl-anc">R$97/user</span><span class="pl-floor">—</span><span class="pl-cond">Sempre iniciar aqui</span></div><div class="pl-row"><span class="pl-lbl">Piso</span><span class="pl-anc">—</span><span class="pl-floor">R$77/user</span><span class="pl-cond">5+ usuarios E contrato anual. Nunca antes.</span></div></div><div class="nota "><span class="nota-i">💡</span><span>Se o cliente pedir desconto: "R$77/user se tiver 5+ usuarios com contrato anual — mas vem com compromisso de 12 meses."</span></div>`,
      t2: `<div class="mental">"O Kora Chat nao e um plano barato. E o primeiro passo inteligente. O cliente que entra aqui ja esta no ecossistema Kora. Em 60 dias voce tem dados reais de volume — e a conversa de upgrade para IA se vende sozinha."</div><div class="ttl2" style="margin-bottom:12px">Como Pensar Essa Venda</div><div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Nao venda como basico — venda como estrategia</div></div><div class="cf-desc">Quem entra pelo Kora Chat nao esta economizando. Esta sendo estrategico: organiza o atendimento antes de escalar.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Use como down-sell inteligente</div></div><div class="cf-desc">Se o cliente travou no setup de R$1.470 do BASE, ofereça o Chat. Ele entra sem risco, voce mantem o relacionamento e o upsell vem.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Plante o upgrade em 60 dias</div></div><div class="cf-desc">Combine uma revisao: "Voce viu X atendimentos esse mes. Imagina se 40% fosse respondido automaticamente pela IA enquanto voce dorme."</div></div></div>`,
      t3: `<div class="hr"><div class="hr-line"></div><div class="hr-lbl">Script de Gancho</div><div class="hr-line"></div></div><div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">Temos um plano sem IA por R$97 por usuario, que e basicamente o Chatwoot conectado ao WhatsApp...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Antes de qualquer automacao, o atendimento precisa estar centralizado. O Kora Chat conecta o WhatsApp e unifica o time numa plataforma profissional. R$97/usuario, sem setup, sem contrato longo. Quando quiser IA — a plataforma ja e a mesma. E so ativar.</div></div></div><div class="hr"><div class="hr-line"></div><div class="hr-lbl">Script de Upsell (60 dias depois)</div><div class="hr-line"></div></div><div class="sb"><div class="sb-lbl">Script</div><p>Nos ultimos 60 dias voce teve X atendimentos no Kora Chat. Desses, quantos eram perguntas repetidas? E exatamente o que o agente BASE faz. Setup R$1.470 unico. Recorrencia adicional R$397/mes. Ja se paga em menos de um mes.</p></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–2 min</div><div class="cf-ttl">Identifique o gargalo</div></div><div class="cf-desc">Quantas mensagens seu time responde por dia? Tudo no WhatsApp pessoal ou tem sistema?</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">2–4 min</div><div class="cf-ttl">Mostre o problema</div></div><div class="cf-desc">Atendimento no pessoal = sem historico, sem metricas. Quando atendente sai, historico some.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">4–5 min</div><div class="cf-ttl">Apresente o Kora Chat</div></div><div class="cf-desc">R$97/usuario, sem setup, sem risco.</div><ul class="cf-ul"><li>Use o script de gancho acima</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">5–6 min</div><div class="cf-ttl">Plante o proximo passo</div></div><ul class="cf-ul"><li>Vamos combinar revisao em 60 dias para ver o volume — e avaliar juntos se faz sentido o agente de IA.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$97 por usuario parece caro para o Chatwoot</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">O Chatwoot e a plataforma. Voce esta contratando a configuracao, integracao WhatsApp Business, suporte tecnico e garantia de que quando quiser IA, nao precisa trocar de ferramenta. E R$3,30/usuario/dia — menos que um cafe.</div><ul class="obj-tips"><li>Enfatize que e plataforma + servico, nao apenas o software</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Por que nao usar o WhatsApp normal?</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag td2">DUVIDA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">WhatsApp pessoal: sem historico centralizado, sem metricas, sem visibilidade do gestor, sem integracao com IA no futuro. O Kora Chat e o atendimento como ativo da empresa, nao do funcionario.</div><ul class="obj-tips"><li>Ressalte o risco de perda de historico</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Prefiro ja entrar com o agente de IA</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tu">TIMING</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Perfeito — entao vamos para o BASE com setup R$1.470. O Kora Chat ja esta incluido no BASE e PLUS. So ofereço separado para quem quer comecar sem IA. Se quer IA direto, BASE e a escolha certa.</div><ul class="obj-tips"><li>Use como qualificador — quem quer IA logo ticketa maior</li></ul></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>WhatsApp Pessoal</th><th>WA Business</th><th class='vk'>Kora Chat</th></tr></thead><tbody><tr><td>Multiplos atendentes</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Historico centralizado</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Parcial</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Metricas e relatorios</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Basico</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Pronto para IA</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim (1-click)</td></tr><tr><td>Custo</td><td class='vy'>✓ Gratis</td><td class='vy'>✓ Gratis</td><td class='vk'>R$97/user/mes</td></tr></tbody></table>`,
    },
  },
  "agent-base": {
    id: "agent-base",
    badge: "KORA AGENT · BASE",
    badgeStyle: "background:rgba(0,229,255,0.08);color:var(--agent);border:1px solid rgba(0,229,255,0.18);",
    name: "AGENT BASE",
    sub: "Agente SDR de IA · Backend invisivel · Sem interface visual",
    tabs: {
      t0: `<div class="ttl2">O que e o AGENT BASE?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Agente de IA rodando em segundo plano. Qualifica leads, responde WhatsApp, integra CRM e envia emails automaticos. Seu time nao ve na tela.</p><div class="nota nota-green"><span class="nota-i">→</span><span>Upgrade natural: quando o cliente quer VER o agente em tempo real, sobe para o PLUS.</span></div><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--agent)">24/7</div><div class="ic-lbl">SDR trabalhando enquanto voce dorme — sem falta, sem atraso.</div></div><div class="ic"><div class="ic-num" style="color:var(--agent)">4x</div><div class="ic-lbl">Promocoes de capacidade — SDR, Vendas, Follow-up, Recuperacao.</div></div><div class="ic"><div class="ic-num" style="color:var(--agent)">30d</div><div class="ic-lbl">Garantia total. Se nao funcionar, 100% do setup devolvido.</div></div><div class="ic"><div class="ic-num" style="color:var(--agent)">R$13</div><div class="ic-lbl">Por dia de recorrencia. Menos que qualquer colaborador no mercado.</div></div></div>`,
      t1: `<div class="ttl2" style="margin-bottom:12px">Precos</div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Setup (ancoragem)</div><div class="pdg-val" style="color:var(--agent)">R$ 1.470</div><div class="pdg-sub">Configuracao + integracao + treinamento</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia (ancoragem)</div><div class="pdg-val" style="color:var(--agent)">R$ 397/mes</div><div class="pdg-sub">Infraestrutura + suporte 48h</div><div class="pdg-cond">R$13/dia — compare com estagiario</div></div><div class="pdg-c"><div class="pdg-lbl">Setup (piso)</div><div class="pdg-val" style="color:var(--gold)">R$ 970</div><div class="pdg-cond">A vista PIX ou boleto</div><div class="pdg-rule">So ceder se cliente pedir explicitamente e fechar na call</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia (piso)</div><div class="pdg-val" style="color:var(--gold)">R$ 337/mes</div><div class="pdg-cond">Debito automatico + contrato 6 meses</div><div class="pdg-rule">Piso absoluto. Abaixo compromete margem.</div></div></div><div class="ttl2" style="margin-bottom:10px;margin-top:18px">Aditivos de Evolucao do Agente</div><table class="vtbl"><thead><tr><th>Promocao</th><th>Aditivo Setup</th><th>Aditivo Rec.</th><th>Quando</th></tr></thead><tbody><tr><td>SDR → Vendas Ativa</td><td>+R$777</td><td>+R$147/mes</td><td>Mes 2-3</td></tr><tr><td>Vendas → Follow-up</td><td>+R$600</td><td>+R$100/mes</td><td>Mes 4-6</td></tr><tr><td>Follow-up → Recuperacao</td><td>+R$700</td><td>+R$120/mes</td><td>Mes 8-12</td></tr><tr><td>Total em aditivos</td><td>R$2.100</td><td>+R$370/mes</td><td>—</td></tr></tbody></table>`,
      t2: `<div class="mental">"O cliente nao esta comprando um agente de IA. Ele esta contratando o primeiro funcionario que nunca vai pedir aumento, nunca falta e trabalha as 3h da manha quando o lead mais quente entrar. Venda isso."</div><div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Custo do Nao Ter</div></div><div class="cf-desc">Quantos leads entram fora do horario sem resposta? Cada lead frio custa mais para reativar do que custa o agente em um mes inteiro.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Comparativo com Estagiario</div></div><div class="cf-desc">R$397/mes = R$13/dia. Um estagiario de vendas custa R$1.470-2k/mes. O agente trabalha 24h, nao 6h. Sem onboarding de 30 dias.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">O Agente Aprende</div></div><div class="cf-desc">No primeiro mes ele treina. No segundo, conhece seu tom e seus produtos. No terceiro, voce o promove a Vendas Ativa. E como contratar um junior que vira senior em 90 dias.</div></div></div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">Nosso agente tem webhook, integracao CRM, automacao de mensagens...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Voce esta perdendo leads toda noite. Mensagens que entram as 23h e so sao respondidas as 9h do dia seguinte — o lead ja esfriou. O agente BASE responde em segundos, qualifica e marca o retorno. R$397/mes. Menos que um dia de vendedor.</div></div></div><div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">O plano BASE e o mais acessivel, depois pode fazer upgrade para o PLUS...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">O agente comeca como SDR — qualificando. Daqui a 60 dias, quando ele souber seu tom e seus produtos, voce o promove a Vendas Ativa. E como um funcionario. So que esse nao pede demissao.</div></div></div><div class="nota nota-blue"><span class="nota-i">ℹ️</span><span>O 1 mes gratis e exclusivo do PLUS e PRO. Se o cliente pede no BASE, use como oportunidade: O primeiro mes gratis e uma exclusividade do PLUS. Quer ver o que muda com a interface completa?</span></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–3 min</div><div class="cf-ttl">Diagnostico de Vazamento</div></div><div class="cf-desc">Quantos leads entram fora do horario? Qual o tempo medio de resposta hoje?</div><ul class="cf-ul"><li>Quanto custa pra voce hoje cada lead que nao foi respondido a tempo?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">3–5 min</div><div class="cf-ttl">Apresente o Agente como Funcionario</div></div><div class="cf-desc">Nao como software — como contratacao estrategica.</div><ul class="cf-ul"><li>Voce esta contratando um SDR. So que esse trabalha 24/7 e nao precisa de 30 dias de onboarding.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">5–7 min</div><div class="cf-ttl">Preco com Contexto</div></div><div class="cf-desc">Setup R$1.470 + R$397/mes. Compare com estagiario (R$1.470-2k/mes).</div><ul class="cf-ul"><li>R$13/dia — impossivel contratar alguem que atende 24/7 por isso</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">7–11 min</div><div class="cf-ttl">Quebra de Objecoes</div></div><div class="cf-desc">Veja a aba de Objecoes.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">11–14 min</div><div class="cf-ttl">Garantia + Proximo Passo</div></div><ul class="cf-ul"><li>30 dias de garantia. Se o agente nao estiver qualificando, devolvo o setup. Quando quer comecar?</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$1.470 de setup e caro</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Quanto custa um estagiario de vendas? R$1.470-2k/mes. O setup e uma vez. A recorrencia de R$397/mes e R$13/dia — impossivel contratar alguem que atende 24/7 por isso. E se em 30 dias sem resultado, devolvo o setup.</div><ul class="obj-tips"><li>Divida por dia: R$13 e mais palatavel que R$397/mes</li><li>Reforce a garantia de 30 dias como eliminador de risco</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Voces sao novos no mercado</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tt">CONFIANCA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Por isso nao pedimos confianca — pedimos 30 dias. Se nao funcionar, devolucao total. Empresas estabelecidas tem mais a perder por nao fazer esforco. Nos temos tudo a ganhar em provar valor.</div><ul class="obj-tips"><li>Transforme novos em vantagem: foco total em provar valor</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Deixa eu pensar...</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tu">URGENCIA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Claro. Mas preciso ser transparente: temos limite de onboardings por mes. Voce topa comecar com o Kora Chat (R$97/usuario) essa semana enquanto decide o BASE? Ja fica na plataforma sem risco.</div><ul class="obj-tips"><li>Use o Chat como down-sell de compromisso minimo</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Preciso falar com meu socio</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tg">DECISAO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Perfeito. Envio documento com resumo, ROI esperado e garantia de 30 dias. Voce mostra pra ele. Marcamos call de 20min com seu socio na proxima semana?</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Estagiario Vendas</th><th>Chatbot Basico</th><th class='vk'>AGENT BASE</th></tr></thead><tbody><tr><td>Custo mensal</td><td>R$1.470-2.000</td><td>R$200-500</td><td class='vk'>R$397/mes</td></tr><tr><td>Disponibilidade</td><td>8h/dia</td><td>24/7</td><td class='vk' class='vy'>✓ 24/7</td></tr><tr><td>Aprende e evolui</td><td class='vy'>✓ Sim</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Tom customizado</td><td class='vy'>✓ Sim</td><td class='vn'>✗ Limitado</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Risco de saida</td><td class='vn'>✗ Alto</td><td class='vy'>✓ Zero</td><td class='vk' class='vy'>✓ Zero</td></tr><tr><td>Garantia 30 dias</td><td class='vn'>✗ Nenhuma</td><td class='vn'>✗ Nenhuma</td><td class='vk' class='vy'>✓ Sim</td></tr></tbody></table>`,
    },
  },
  "agent-plus": {
    id: "agent-plus",
    badge: "KORA AGENT · PLUS",
    badgeStyle: "background:rgba(124,111,255,0.1);color:var(--purple);border:1px solid rgba(124,111,255,0.22);",
    name: "AGENT PLUS",
    sub: "Agente + Kora Chat · Time ve o agente ao vivo · 3 licencas",
    tabs: {
      t0: `<div class="mfb"><span class="mfb-badge">1&ordm; MES GRATIS</span><p>Ao fechar o PLUS, o <strong>primeiro mes de recorrencia e gratuito</strong>. Use como argumento de fechamento — nao entregue antes de ser pedido.</p></div><div class="ttl2">O que muda em relacao ao BASE?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">No BASE o agente trabalha em segundo plano. No PLUS voce abre o Kora Chat e ve o agente em acao em tempo real. O time pode intervir, ajustar tom e acompanhar cada conversa.</p><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--purple)">3</div><div class="ic-lbl">Licencas operacionais incluidas no Kora Chat.</div></div><div class="ic"><div class="ic-num" style="color:var(--purple)">Real-time</div><div class="ic-lbl">Time ve e pode intervir nas conversas do agente ao vivo.</div></div><div class="ic"><div class="ic-num" style="color:var(--purple)">Mesmo</div><div class="ic-lbl">Agente evolui igual — mesmas 4 promocoes e aditivos do BASE.</div></div><div class="ic"><div class="ic-num" style="color:var(--purple)">R$0</div><div class="ic-lbl">No primeiro mes de recorrencia ao fechar.</div></div></div>`,
      t1: `<div class="mfb"><span class="mfb-badge">1&ordm; MES GRATIS</span><p>Recorrencia do 1 mes zerada ao fechar. Setup cobrado normalmente.</p></div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Setup (ancoragem)</div><div class="pdg-val" style="color:var(--purple)">R$ 3.470</div><div class="pdg-sub">Kora Chat + 3 licencas + agente treinado</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia (ancoragem)</div><div class="pdg-val" style="color:var(--purple)">R$ 647/mes</div><div class="pdg-sub">1 mes gratis — cobra do 2 mes em diante</div></div><div class="pdg-c"><div class="pdg-lbl">Setup (piso)</div><div class="pdg-val" style="color:var(--gold)">R$ 2.770</div><div class="pdg-cond">A vista PIX + depoimento video 60 dias</div><div class="pdg-rule">Piso absoluto. Nao ceder sem contrapartida.</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia (piso)</div><div class="pdg-val" style="color:var(--gold)">R$ 577/mes</div><div class="pdg-cond">Debito automatico + contrato 6 meses</div><div class="pdg-rule">Abaixo de R$577 redirecione para o BASE.</div></div></div><div class="nota "><span class="nota-i">💡</span><span>Script do 1 mes gratis: "O setup e R$3.470 e a recorrencia e R$647/mes. Mas como quero que voce experimente sem risco, o primeiro mes de mensalidade e por nossa conta. Voce so começa a pagar no segundo mes, quando ja viu o agente trabalhando."</span></div>`,
      t2: `<div class="mental">"A diferenca entre BASE e PLUS nao e so interface. E controle. O gestor que quer VER o que o agente faz, intervir quando precisa — esse e cliente PLUS. Venda visibilidade, nao features."</div><div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Para quem e o PLUS</div></div><div class="cf-desc">Clientes com time comercial ativo. O gestor quer ver o dashboard, o time quer acompanhar as conversas. Se nao tem time, BASE e suficiente.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">O 1 Mes Gratis como fechador</div></div><div class="cf-desc">Use como ultimo recurso antes de ceder no preco. Nao consigo baixar o setup, mas consigo zerar a primeira mensalidade. Voce comeca a pagar so quando ja viu o agente trabalhando.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Upgrade BASE para PLUS</div></div><div class="cf-desc">Para clientes ja no BASE: Voce ja validou que o agente funciona. O proximo passo e dar visibilidade pro time. Aditivo de R$2.000 setup e +R$250/mes.</div></div></div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">O PLUS tem o Kora Chat que e um Chatwoot white label com 3 licencas operacionais...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">BASE: o agente trabalha. PLUS: voce VE o agente trabalhando. Seu time abre o Kora Chat e ve cada conversa ao vivo. Pode entrar com um clique. E a diferenca entre ter um funcionario remoto que voce nao ve, e um que senta do seu lado.</div></div></div><div class="sb"><div class="sb-lbl">Script do 1 Mes Gratis — use como ultimo argumento antes de ceder no preco</div><p>Olha, o setup eu nao consigo mexer — e o custo real de engenharia. Mas o que consigo fazer pelo PLUS e zerar o primeiro mes de recorrencia. Voce paga o setup, a gente ativa tudo, e voce comeca a pagar os R$647 so no segundo mes, quando ja viu o agente qualificando na tela. Isso resolve?</p></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–3 min</div><div class="cf-ttl">Pergunta de Visibilidade</div></div><div class="cf-desc">Qualificador-chave para PLUS.</div><ul class="cf-ul"><li>Seu time precisa VER o agente trabalhando, ou pode rodar em segundo plano?</li><li>Se VER → PLUS. Se segundo plano → BASE.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">3–6 min</div><div class="cf-ttl">Demo Mental do Kora Chat</div></div><div class="cf-desc">Descreva a experiencia, nao a ferramenta.</div><ul class="cf-ul"><li>Imagine seu gestor abrindo uma tela e vendo todas as conversas do agente ao vivo. Podendo entrar em qualquer uma com um clique.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">6–8 min</div><div class="cf-ttl">Preco + 1 Mes Gratis</div></div><div class="cf-desc">Setup R$3.470 + R$647/mes. Primeiro mes de recorrencia por nossa conta.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">8–12 min</div><div class="cf-ttl">Quebra de Objecoes</div></div><div class="cf-desc">Veja a aba de Objecoes.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">12–14 min</div><div class="cf-ttl">Fechamento</div></div><ul class="cf-ul"><li>Setup R$3.470. Primeiro mes de recorrencia por nossa conta. Quando posso agendar o kick-off tecnico?</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$3.470 de setup e muito</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Duas opcoes: a) 50% de entrada e 50% na homologacao — so paga o restante quando ve o sistema rodando. b) Zerar o primeiro mes de recorrencia — paga R$3.470 agora e comeca a mensalidade so em 60 dias.</div><ul class="obj-tips"><li>Opcao a: parcelamento por marcos — menos risco percebido</li><li>Opcao b: 1 mes gratis — valor percebido maior</li><li>Se ainda resistir: ofereça o BASE (R$1.470 setup) como entrada</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Por que preciso do Kora Chat se o BASE ja faz tudo?</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag td2">DUVIDA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">BASE e para quem confia que o agente funciona sem supervisao. PLUS e para quem quer controle e visibilidade. Se voce tem um gestor que vai querer acompanhar, o PLUS e o certo.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>Como confio no setup sendo novos?</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tt">CONFIANCA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Por isso o parcelamento por marcos. Voce paga 50% para iniciar. Paga os outros 50% so na homologacao, quando ve tudo rodando na tela. Nunca paga pelo que nao viu funcionar.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Time SDR (2 pessoas)</th><th>CRM + Chatbot</th><th class='vk'>AGENT PLUS</th></tr></thead><tbody><tr><td>Custo mensal</td><td>R$6.000-8.000</td><td>R$777-1.500</td><td class='vk'>R$647/mes</td></tr><tr><td>Disponibilidade 24/7</td><td class='vn'>✗ Nao</td><td class='vy'>✓ Sim</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Visibilidade real-time</td><td class='vy'>✓ Sim</td><td class='vn'>✗ Limitada</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Aprende e evolui</td><td class='vy'>✓ Sim</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>1 mes gratis</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Garantia 30 dias</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr></tbody></table>`,
    },
  },
  "agent-pro": {
    id: "agent-pro",
    badge: "KORA AGENT · PRO",
    badgeStyle: "background:rgba(255,209,102,0.1);color:var(--gold);border:1px solid rgba(255,209,102,0.2);",
    name: "AGENT PROFESSIONAL",
    sub: "Agente + Chat + Dashboard 360 + Comite Mensal",
    tabs: {
      t0: `<div class="mfb"><span class="mfb-badge">1&ordm; MES GRATIS</span><p>Ao fechar o PROFESSIONAL, o <strong>primeiro mes de recorrencia e gratuito</strong>.</p></div><div class="ttl2">O que e o PROFESSIONAL?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Tudo do PLUS mais Dashboard de Gestao 360 com analytics e funnels em tempo real, e comite mensal de 1h com a equipe Koraflow.</p><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--gold)">360°</div><div class="ic-lbl">Dashboard com analytics, funnels e ROI real-time.</div></div><div class="ic"><div class="ic-num" style="color:var(--gold)">1h/mes</div><div class="ic-lbl">Comite com equipe Koraflow para insights e refinamento.</div></div><div class="ic"><div class="ic-num" style="color:var(--gold)">Parceria</div><div class="ic-lbl">Nao e so automacao — e inteligencia estrategica de longo prazo.</div></div><div class="ic"><div class="ic-num" style="color:var(--gold)">R$0</div><div class="ic-lbl">No primeiro mes de recorrencia ao fechar.</div></div></div>`,
      t1: `<div class="mfb"><span class="mfb-badge">1&ordm; MES GRATIS</span><p>Recorrencia do 1 mes zerada. Setup cobrado normalmente.</p></div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Setup (ancoragem)</div><div class="pdg-val" style="color:var(--gold)">R$ 6.470</div><div class="pdg-sub">Agente + Kora Chat + Dashboard + integracao</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia (ancoragem)</div><div class="pdg-val" style="color:var(--gold)">R$ 897/mes</div><div class="pdg-sub">1 mes gratis — cobra do 2 mes em diante</div></div><div class="pdg-c"><div class="pdg-lbl">Setup (piso secreto)</div><div class="pdg-val" style="color:var(--studio)">R$ 4.970</div><div class="pdg-cond">A vista PIX + depoimento video 60 dias + case estudo</div><div class="pdg-rule">Piso absoluto. Exige contrapartida. So revelar se travar na mesa.</div></div><div class="pdg-c"><div class="pdg-lbl">Recorrencia (piso)</div><div class="pdg-val" style="color:var(--studio)">R$ 777/mes</div><div class="pdg-cond">Contrato anual + debito automatico</div><div class="pdg-rule">Nao ceder sem contrato anual assinado.</div></div></div>`,
      t2: `<div class="mental">"PROFESSIONAL nao e para quem esta comecando. E para quem ja viu resultado e quer parceria estrategica. Voce nao esta vendendo um produto — esta vendendo um seat no comite de inteligencia da empresa deles."</div><div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">Perfil do Cliente PRO</div></div><div class="cf-desc">Ja usa automacao, tem time estruturado. Quer dados para decisao e nao quer apenas ferramentas — quer um parceiro que pensa junto.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">O Comite como Diferencial</div></div><div class="cf-desc">A maioria das ferramentas entrega e some. O comite mensal e o que diferencia: Koraflow fica responsavel pelo resultado, nao so pela entrega.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-ttl">O 1 Mes Gratis no PRO</div></div><div class="cf-desc">Com setup de R$6.470, o 1 mes gratis representa R$897 de economia imediata. Argumento forte ao fechar.</div></div></div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">O Professional tem dashboard de gestao 360 com analytics, funnels, ROI real-time e comite mensal...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">PLUS e operacional. PRO e estrategico. No PLUS o agente trabalha e voce ve. No PRO a gente senta contigo uma vez por mes, olha os dados e decide juntos o que otimizar. Nao e ferramenta — e parceiro de inteligencia comercial.</div></div></div><div class="sb"><div class="sb-lbl">Script do 1 Mes Gratis — PRO</div><p>O setup do PRO e R$6.470. Mas porque quero que voce entre com confianca total, o primeiro mes de recorrencia — R$897 — e por nossa conta. Voce so comeca a pagar a mensalidade no segundo mes, quando ja participou do primeiro comite de insights e viu o dashboard com dados reais do seu negocio.</p></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–3 min</div><div class="cf-ttl">Qualifique o Perfil PRO</div></div><ul class="cf-ul"><li>Voce ja usa alguma automacao hoje? Tem alguem olhando metricas comerciais regularmente?</li><li>Sim para os dois → PRO. Nao → comece pelo PLUS.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">3–6 min</div><div class="cf-ttl">Venda a Parceria, nao o Produto</div></div><ul class="cf-ul"><li>A diferenca do PRO e que a gente fica responsavel pelo resultado. Todo mes a gente senta junto, olha os dados e decide o que ajustar. Nao esta comprando software — esta contratando parceiro de inteligencia.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">6–8 min</div><div class="cf-ttl">Preco + 1 Mes Gratis</div></div><ul class="cf-ul"><li>R$6.470 setup + R$897/mes. Primeiro mes de recorrencia por nossa conta.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">8–12 min</div><div class="cf-ttl">Quebra de Objecoes</div></div><div class="cf-desc">Veja a aba de Objecoes.</div></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">12–14 min</div><div class="cf-ttl">Fechamento</div></div><ul class="cf-ul"><li>Quando quer fazer o primeiro comite? Posso reservar uma quinta de tarde do mes que vem.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$6.470 de setup travou a mesa</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Duas opcoes: a) Parcelamento por marcos — 50% agora, 50% na homologacao. b) Piso secreto: consigo R$4.970 a vista se a contrapartida for um depoimento em video de 3min detalhando o ROI apos 60 dias.</div><ul class="obj-tips"><li>Opcao a: parcelamento por marcos — ideal se quer reduzir risco</li><li>Opcao b: depoimento como contrapartida — posicionar como parceria, nao desconto</li></ul></div></div><div class="obj-item"><button class="obj-trigger"><span>Ja tenho PLUS, por que migrar para PRO?</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag td2">DUVIDA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">PLUS e operacional — voce ve o agente. PRO e estrategico — a gente analisa os dados juntos e decide o proximo movimento. Se quer tomar decisoes baseado em dados reais, PRO e o que faz sentido.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Consultor Externo</th><th>BI Interno</th><th class='vk'>AGENT PRO</th></tr></thead><tbody><tr><td>Custo mensal</td><td>R$4.970-15.000</td><td>R$8.000-20.000</td><td class='vk'>R$897/mes</td></tr><tr><td>Agente de IA ativo</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim (24/7)</td></tr><tr><td>Dashboard real-time</td><td class='vn'>✗ Nao</td><td class='vy'>✓ Sim</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Comite mensal</td><td class='vy'>✓ Sim</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>1 mes gratis</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr></tbody></table>`,
    },
  },
  "dev-start": {
    id: "dev-start",
    badge: "KORA DEV · START",
    badgeStyle: "background:rgba(0,255,159,0.07);color:var(--dev);border:1px solid rgba(0,255,159,0.18);",
    name: "DEV START",
    sub: "Retainer 10h mensais · Suporte, bugs e seguranca",
    tabs: {
      t0: `<div class="ttl2">O que e o DEV START?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">10 horas mensais dedicadas de engenharia senior para manutencao, bugs e atualizacoes de seguranca. Usa ou perde no mes — nao acumula.</p><div class="nota "><span class="nota-i">⚡</span><span><strong>Acionamento avulso: R$347</strong> para qualquer sprint tecnico fora do retainer. Nao negocie isso.</span></div><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--dev)">10h</div><div class="ic-lbl">Senior dedicadas por mes. Sem surpresa de orcamento.</div></div><div class="ic"><div class="ic-num" style="color:var(--dev)">SLA</div><div class="ic-lbl">Prioridade em bugs criticos. Resposta em 24h uteis.</div></div></div>`,
      t1: `<div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--dev)">R$ 1.197/mes</div><div class="pdg-sub">Padrao</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--gold)">R$ 970/mes</div><div class="pdg-cond">Boleto automatizado ou debito em conta</div><div class="pdg-rule">Nao ceder sem essa condicao. Boleto manual = risco de inadimplencia.</div></div></div>`,
      t2: `<div class="mental">"O START nao e barato — e previsivel. O cliente nao quer surpresa de fatura. Quer saber que tem 10h de senior disponivel todo mes sem burocracia de orcamento."</div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">Temos um retainer de 10 horas por R$1.197 com manutencao e bugs...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Todo mes tem algo quebrando. Uma atualizacao de seguranca, um bug que o cliente reportou, um ajuste de integracao. Voce nao quer ficar pedindo orcamento toda vez. O START e seu fundo fixo de engenharia: 10h senior, disponivel toda semana.</div></div></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–2 min</div><div class="cf-ttl">Diagnostique a Dor</div></div><ul class="cf-ul"><li>Quando aparece um bug critico hoje, qual e o processo? Voce tem quem chamar em 24h?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">2–4 min</div><div class="cf-ttl">Apresente Previsibilidade</div></div><ul class="cf-ul"><li>10h mensais fixas. Voce nao pede orcamento, nao espera proposta. Liga, abre o chamado, a gente resolve.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">4–6 min</div><div class="cf-ttl">Preco + Condicao de Piso</div></div><ul class="cf-ul"><li>R$1.197 padrao. Se pedir desconto: R$970 se fechar com boleto automatico ou debito — elimina inadimplencia e consigo repassar a economia.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>10h parece pouco</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tn">ESCOPO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Se voce precisa de evolucao de produto, o PLUS com 20h e mais adequado. Vamos mapear o que precisa nos proximos 3 meses — se couber em 10h, START e certo. Se nao, o PLUS cobre com folga.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>Nao uso 10h todos os meses</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag td2">DUVIDA</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">O valor do retainer nao e so as horas — e a disponibilidade. Voce esta pagando para ter engenharia senior disponivel quando precisar. Mes que nao usar muito = paz de espirito. Mes que precisar muito = horas la.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Freelancer</th><th>Dev Junior CLT</th><th class='vk'>DEV START</th></tr></thead><tbody><tr><td>Custo mensal</td><td>Variavel</td><td>R$3.000-4.000</td><td class='vk'>R$970-1.200</td></tr><tr><td>Nivel tecnico</td><td>Variavel</td><td>Junior</td><td class='vk' class='vy'>✓ Senior</td></tr><tr><td>Disponibilidade</td><td class='vn'>✗ Nao garantida</td><td>8h/dia</td><td class='vk' class='vy'>✓ SLA 24h</td></tr><tr><td>Sem CLT/encargos</td><td class='vy'>✓ Sim</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr></tbody></table>`,
    },
  },
  "dev-plus": {
    id: "dev-plus",
    badge: "KORA DEV · PLUS",
    badgeStyle: "background:rgba(0,255,159,0.07);color:var(--dev);border:1px solid rgba(0,255,159,0.18);",
    name: "DEV PLUS",
    sub: "Landing Page Premium OU Retainer 20h",
    tabs: {
      t0: `<div class="ttl2">O que e o DEV PLUS?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Dois modelos: LP Premium (entrega unica com foco em UX, velocidade e conversao) ou Retainer de 20h mensais para evolucao continua de plataforma.</p><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--dev)">Grade A</div><div class="ic-lbl">Speed e Core Web Vitals. Cada segundo a menos = +7% de conversao.</div></div><div class="ic"><div class="ic-num" style="color:var(--dev)">20h</div><div class="ic-lbl">Retainer com horas para evolucao real de produto.</div></div></div>`,
      t1: `<div class="ttl2" style="margin-bottom:10px">LP Premium (entrega unica)</div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--dev)">R$ 2.470</div><div class="pdg-sub">Ate 3x no cartao</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--gold)">R$ 1.870</div><div class="pdg-cond">A vista PIX</div></div></div><div class="ttl2" style="margin-bottom:10px;margin-top:18px">Retainer 20h/mes</div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--dev)">R$ 2.170/mes</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--gold)">R$ 1.770/mes</div><div class="pdg-cond">Contrato 3 meses</div></div></div>`,
      t2: `<div class="mental">"Cada segundo a mais de carregamento custa 7% de conversao. Uma LP lenta ja esta custando vendas hoje. Nao venda desenvolvimento — venda receita perdida que a gente vai recuperar."</div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">Fazemos landing pages com Core Web Vitals, Pixel do Facebook, GA4...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Sua pagina atual leva quantos segundos para carregar? Cada segundo acima de 2 custa 7% de conversao. Se voce investe em trafego e a pagina e lenta, esta jogando dinheiro fora. A gente entrega Grade A em velocidade — porque isso e diretamente receita.</div></div></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–2 min</div><div class="cf-ttl">Teste a Pagina Atual</div></div><ul class="cf-ul"><li>Qual e o URL? Sabe quanto tempo leva para carregar no celular?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">2–5 min</div><div class="cf-ttl">Quantifique a Perda</div></div><ul class="cf-ul"><li>Se voce investe R$4.970/mes em trafego e a pagina converte 2% — uma LP otimizada pode levar isso para 4-6%. O dobro de leads sem gastar mais em anuncio.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">5–7 min</div><div class="cf-ttl">LP ou Retainer?</div></div><ul class="cf-ul"><li>Voce precisa de uma entrega nova (LP) ou de evolucao continua do que ja tem (retainer)?</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$2.470 por uma LP parece caro</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Agencia digital cobra R$4.970-15.000 por LP nesse nivel tecnico. Se voce investe R$3.000/mes em trafego e a LP converte 3% — melhorar para 5% gera 66% mais leads. O R$2.470 se paga no primeiro mes.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>Prefiro contratar um freelancer</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tt">COMPETICAO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Freelancer entrega o codigo e some. Bug apareceu? Orcamento novo. A gente entrega e fica — retainer de sustentacao disponivel. Nao e so entrega, e continuidade.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Freelancer</th><th>Agencia Digital</th><th class='vk'>DEV PLUS</th></tr></thead><tbody><tr><td>Custo LP</td><td>R$777-2.000</td><td>R$4.970-15.000</td><td class='vk'>R$1.870-2.500</td></tr><tr><td>Speed Grade A</td><td>Variavel</td><td class='vn'>✗ Nem sempre</td><td class='vk' class='vy'>✓ Garantido</td></tr><tr><td>Sustentacao pos-entrega</td><td class='vn'>✗ Nao</td><td>Paga extra</td><td class='vk' class='vy'>✓ Disponivel</td></tr></tbody></table>`,
    },
  },
  "dev-pro": {
    id: "dev-pro",
    badge: "KORA DEV · PRO",
    badgeStyle: "background:rgba(255,209,102,0.08);color:var(--gold);border:1px solid rgba(255,209,102,0.18);",
    name: "DEV PROFESSIONAL",
    sub: "SaaS/App completo OU Retainer 40h + Consultoria de Arquitetura",
    tabs: {
      t0: `<div class="ttl2">O que e o DEV PROFESSIONAL?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Sistemas e aplicacoes completas do zero (SaaS) com arquitetura Serverless e Supabase, ou Retainer de 40h mensais com Consultoria de Arquitetura e inovacao continua.</p><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--gold)">SaaS</div><div class="ic-lbl">Produto proprio desenvolvido do zero com arquitetura escalavel.</div></div><div class="ic"><div class="ic-num" style="color:var(--gold)">CTO</div><div class="ic-lbl">Retainer 40h age como seu CTO externo — sem CLT, sem FGTS.</div></div></div>`,
      t1: `<div class="ttl2" style="margin-bottom:10px">Setup SaaS/App</div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--gold)">A partir R$ 16k</div><div class="pdg-sub">Ate 5x no cartao</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--gold)">A partir R$ 13.470</div><div class="pdg-cond">Marcos 40/30/30</div><div class="pdg-rule">40% inicio, 30% meio, 30% entrega. Nunca negocie sem marcos definidos.</div></div></div><div class="ttl2" style="margin-bottom:10px;margin-top:18px">Sustentacao Mensal</div><div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--gold)">R$ 897/mes</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--studio)">R$ 747/mes</div><div class="pdg-cond">Contrato anual</div></div></div>`,
      t2: `<div class="mental">"Voce nao esta vendendo desenvolvimento. Esta vendendo o produto que esse cliente sempre quis ter mas nao sabia como construir. Posicione-se como CTO externo — parceiro tecnico de longo prazo, nao fornecedor de horas."</div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">Desenvolvemos em arquitetura Serverless com Supabase, escalabilidade horizontal...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Voce quer construir um produto proprio mas nao quer montar um time de dev agora. A gente e o seu CTO externo. Entregamos o sistema, documentamos tudo e continuamos como parceiros tecnicos. Sem CLT, sem FGTS, sem processo seletivo de 3 meses.</div></div></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–3 min</div><div class="cf-ttl">Entenda a Visao do Produto</div></div><ul class="cf-ul"><li>O que voce quer construir? Qual problema resolve? Quem e o usuario?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">3–6 min</div><div class="cf-ttl">Posicione como CTO</div></div><ul class="cf-ul"><li>A gente nao entrega codigo e some. A gente fica como parceiro tecnico — reuniao quinzenal, roadmap, decisoes de arquitetura juntos.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">6–9 min</div><div class="cf-ttl">Marcos e Preco</div></div><ul class="cf-ul"><li>Setup a partir de R$15.970 dividido em marcos — 40% para iniciar, 30% no meio, 30% na entrega. Voce so paga mais quando ve o produto evoluindo.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$15.970 e muito para comecar</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">R$15.970 uma vez vs R$20-30k/mes de um time proprio. No primeiro mes de time interno voce ja pagou mais. E o setup e dividido em 3 marcos — so desembolsa 40% agora.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>Prefiro contratar dev interno</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tt">COMPETICAO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Dev senior CLT: R$12-18k/mes bruto + 70% encargos = R$20-30k custo real. Processo seletivo de 2-3 meses. Risco de saida. Com a gente: custo fixo, sem encargos, ja rodando em 2 semanas.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Dev Senior CLT</th><th>Agencia Grande</th><th class='vk'>DEV PRO</th></tr></thead><tbody><tr><td>Custo mensal real</td><td>R$20.000-30.000</td><td>R$15.000-40.000</td><td class='vk'>R$747-900/mes</td></tr><tr><td>Time to start</td><td>2-3 meses</td><td>1 mes</td><td class='vk' class='vy'>✓ 2 semanas</td></tr><tr><td>Responsabilidade resultado</td><td class='vy'>✓ Alta</td><td class='vn'>✗ Baixa</td><td class='vk' class='vy'>✓ Alta</td></tr></tbody></table>`,
    },
  },
  "studio-start": {
    id: "studio-start",
    badge: "KORA STUDIO · START",
    badgeStyle: "background:rgba(255,107,107,0.07);color:var(--studio);border:1px solid rgba(255,107,107,0.18);",
    name: "STUDIO START",
    sub: "Video Premium ou 25 Fotos IA · Venda unica",
    tabs: {
      t0: `<div class="ttl2">O que e o STUDIO START?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Producao audiovisual avulsa: 1 Video Premium (ate 45s com roteiro, locucao, SFX e IA Cinematica) ou Lote de 25 Fotos IA de Alta Resolucao.</p><div class="nota nota-red"><span class="nota-i">⚠️</span><span><strong>Clausula anti-refacao:</strong> Max 2 rodadas. Extra: R$147/render. Mencione no inicio — nunca como surpresa.</span></div><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--studio)">45s</div><div class="ic-lbl">Video com roteiro, locucao profissional, SFX e IA cinematica.</div></div><div class="ic"><div class="ic-num" style="color:var(--studio)">25</div><div class="ic-lbl">Fotos IA alta resolucao para campanhas, site e social.</div></div></div>`,
      t1: `<div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--studio)">R$ 1.197</div><div class="pdg-sub">Ate 2x no cartao</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--gold)">R$ 947</div><div class="pdg-cond">A vista PIX</div><div class="pdg-rule">Nao ceder sem PIX a vista. Abaixo de R$947 compromete producao.</div></div></div>`,
      t2: `<div class="mental">"O START e a prova de conceito. O cliente que aprova a qualidade aqui entra no PLUS trimestral sem medo. Entregue algo que ele vai querer mostrar pra todo mundo."</div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">Fazemos videos com IA cinematica, SFX, roteiro personalizado...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Seu concorrente esta postando conteudo profissional toda semana. Sem um ativo de video de impacto, sua marca parece amadora comparada a quem investe em producao. Um video de 45s bem feito muda a percepcao de valor do seu produto inteiro.</div></div></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–2 min</div><div class="cf-ttl">Presenca Visual Atual</div></div><ul class="cf-ul"><li>Quando foi o ultimo video profissional? Como esta a qualidade visual comparada ao seu maior concorrente?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">2–4 min</div><div class="cf-ttl">ROI do Ativo</div></div><ul class="cf-ul"><li>Um video de impacto roda por 6-12 meses. R$1.197 por um ativo que representa sua marca esse tempo todo — menos que um dia de anuncio no Meta.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">4–5 min</div><div class="cf-ttl">Plante o PLUS</div></div><ul class="cf-ul"><li>Esse video e a porta de entrada. Se gostar da qualidade, temos um plano trimestral que mantem esse ritmo todo mes por R$1.770.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>R$1.197 por um video parece caro</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Videomaker freelancer cobra R$2.000-5.000 sem IA cinematica. Agencia: R$8.000-20.000. A gente entrega o mesmo padrao com IA por R$1.197 (ou R$947 PIX). Um dia de anuncio no Meta custa mais.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>Posso alterar quantas vezes?</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tn">PROCESSO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">2 rodadas incluidas — suficientes para refinamentos. Antes de produzir fazemos sessao de alinhamento: voce aprova roteiro, referencias e estetica. Isso elimina a necessidade de mais rodadas.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Freelancer</th><th>Agencia</th><th class='vk'>STUDIO START</th></tr></thead><tbody><tr><td>Custo video</td><td>R$2.000-5.000</td><td>R$8.000-20.000</td><td class='vk'>R$947-1.200</td></tr><tr><td>IA Cinematica</td><td class='vn'>✗ Raramente</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Roteiro incluso</td><td class='vn'>✗ Paga extra</td><td class='vy'>✓ Sim</td><td class='vk' class='vy'>✓ Sim</td></tr></tbody></table>`,
    },
  },
  "studio-plus": {
    id: "studio-plus",
    badge: "KORA STUDIO · PLUS",
    badgeStyle: "background:rgba(255,107,107,0.07);color:var(--studio);border:1px solid rgba(255,107,107,0.18);",
    name: "STUDIO PLUS",
    sub: "Kora Campaign · Trimestral · Conteudo recorrente de alto padrao",
    tabs: {
      t0: `<div class="ttl2">O que e o STUDIO PLUS?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Plano trimestral: 1 Filme 30s + 4 Reels + 2 Carroseis + assets visuais + copys + planejamento. Todo mes. A consistencia que o algoritmo e o publico recompensam.</p><div class="nota nota-red"><span class="nota-i">⚠️</span><span>Clausula anti-refacao se aplica. Multa de 30% em rescisao antecipada.</span></div>`,
      t1: `<div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--studio)">R$ 1.770/mes</div><div class="pdg-sub">Fidelidade trimestral</div></div><div class="pdg-c"><div class="pdg-lbl">Piso</div><div class="pdg-val" style="color:var(--gold)">R$ 1.530/mes</div><div class="pdg-cond">Contrato com multa de 30% em rescisao antecipada</div></div></div>`,
      t2: `<div class="mental">"Conteudo so funciona com consistencia. Uma campanha isolada nao constroi audiencia. O que muda o jogo e 3 meses de presenca constante — o algoritmo aprende, o publico confia, o resultado aparece."</div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">No plano Plus voce tem 1 filme + 4 reels + 2 carroseis com planejamento trimestral...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Seu concorrente esta postando 3-4 vezes por semana. Cada semana sem conteudo e share of attention cedido de graca. O Plus garante presenca constante — filme, reels, carroseis — sem voce pensar nisso. A gente pensa, voce aprova, a gente publica.</div></div></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–2 min</div><div class="cf-ttl">Frequencia Atual</div></div><ul class="cf-ul"><li>Com que frequencia voce publica hoje? Quem produz o conteudo?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">2–4 min</div><div class="cf-ttl">Gap de Consistencia</div></div><ul class="cf-ul"><li>3 meses de inconsistencia custam mais do que 3 meses de investimento. O algoritmo pune quem some.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">4–6 min</div><div class="cf-ttl">Proposta do Trimestral</div></div><ul class="cf-ul"><li>O minimo para ver ROI de conteudo e 3 meses. O PLUS e exatamente isso — depois voce decide se continua.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>Nao gosto de contratos com fidelidade</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">CONTRATO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">A fidelidade existe porque conteudo tem resultado cumulativo — nao ve impacto em 1 mes. A multa de 30% protege os dois lados. Mas olha: comece pelo START — um video, sem contrato. Aprova a qualidade, depois entramos no trimestral confiantes.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>R$1.770/mes e caro para conteudo</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">PRECO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Social media planner (R$3k) + videomaker (R$5k/projeto) + designer (R$2k) = R$10k+/mes. A gente entrega tudo por R$1.770. Onde mais voce encontra isso?</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>SM + Videomaker</th><th>Agencia</th><th class='vk'>STUDIO PLUS</th></tr></thead><tbody><tr><td>Custo mensal</td><td>R$4.970-10.000</td><td>R$4.000-8.000</td><td class='vk'>R$1.530-1.800</td></tr><tr><td>IA na producao</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Raramente</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Tudo incluso</td><td class='vn'>✗ Separado</td><td class='vy'>✓ Sim</td><td class='vk' class='vy'>✓ Sim</td></tr></tbody></table>`,
    },
  },
  "studio-pro": {
    id: "studio-pro",
    badge: "KORA STUDIO · PRO",
    badgeStyle: "background:rgba(255,209,102,0.08);color:var(--gold);border:1px solid rgba(255,209,102,0.18);",
    name: "STUDIO PROFESSIONAL",
    sub: "Direcao de Arte + Brandbook IA + Comite Mensal",
    tabs: {
      t0: `<div class="ttl2">O que e o STUDIO PROFESSIONAL?</div><p style="color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:16px">Tudo do PLUS mensalmente, mais Consultoria Premium Elite, Brandbook guiado por IA e Comite Mensal de Insights e Tendencias de Marca.</p><div class="col2"><div class="ic"><div class="ic-num" style="color:var(--gold)">Brand</div><div class="ic-lbl">Brandbook guiado por IA — identidade visual solida e consistente.</div></div><div class="ic"><div class="ic-num" style="color:var(--gold)">Comite</div><div class="ic-lbl">Reuniao mensal de tendencias e insights com equipe Koraflow.</div></div></div>`,
      t1: `<div class="pdg"><div class="pdg-c"><div class="pdg-lbl">Ancoragem</div><div class="pdg-val" style="color:var(--gold)">R$ 1.470/mes</div><div class="pdg-sub">Fidelidade anual</div></div><div class="pdg-c"><div class="pdg-lbl">Piso Secreto</div><div class="pdg-val" style="color:var(--studio)">R$ 1.230/mes</div><div class="pdg-cond">Cartao recorrente ativo</div><div class="pdg-rule">Piso absoluto. So revelar se cliente travar no anual.</div></div></div>`,
      t2: `<div class="mental">"O PRO e para quem ja investe em conteudo mas sente que a marca nao tem identidade solida. Cada peca parece de uma empresa diferente. O PRO solidifica quem voce e — garante que todo conteudo futuro reforce a mesma marca."</div>`,
      t3: `<div class="ed-grid"><div class="ec-card ec-ev"><div class="ec-lbl">✗ Evite</div><div class="ec-txt">O Professional tem brandbook com IA mais comite mensal de insights e tendencias...</div></div><div class="ec-card ec-di"><div class="ec-lbl">✓ Diga</div><div class="ec-txt">Voce ja investe em conteudo. Mas sem identidade visual solida, cada peca parece de uma marca diferente. O PRO solidifica quem voce e. Brandbook, direcao de arte, reuniao mensal — tudo pra garantir que o que publicamos reforca a marca, nao fragmenta ela.</div></div></div>`,
      t4: `<div class="cf"><div class="cf-step"><div class="cf-hd"><div class="cf-time">0–2 min</div><div class="cf-ttl">Diagnostico de Identidade</div></div><ul class="cf-ul"><li>Se eu abrir seu Instagram e o do seu concorrente, da pra distinguir as marcas sem ver o nome?</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">2–5 min</div><div class="cf-ttl">Posicione o Brandbook</div></div><ul class="cf-ul"><li>O brandbook e o GPS criativo da sua marca. Com ele, qualquer peca que produzirmos vai parecer da mesma empresa.</li></ul></div><div class="cf-step"><div class="cf-hd"><div class="cf-time">5–7 min</div><div class="cf-ttl">Preco + Piso Secreto</div></div><ul class="cf-ul"><li>R$1.470/mes anual. Se travar: Consigo R$1.230/mes via cartao recorrente ativo.</li></ul></div></div>`,
      t5: `<div class="obj-list"><div class="obj-item"><button class="obj-trigger"><span>Ja temos uma agencia</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tt">COMPETICAO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">A gente nao compete — complementa. Muitos clientes mantiveram a agencia para relacionamento e vieram pra nos para producao com IA e brandbook estruturado. O diferencial e a integracao com IA que agencia tradicional nao entrega.</div></div></div><div class="obj-item"><button class="obj-trigger"><span>Anual e muito compromisso</span><div style="display:flex;align-items:center;gap:8px"><span class="obj-tag tp">CONTRATO</span><span class="obj-chev">&#9662;</span></div></button><div class="obj-body"><div class="obj-resp">Comece pelo PLUS trimestral. Aprova a qualidade em 3 meses — ai a conversa do anual com PRO se faz sozinha com dados reais.</div></div></div></div>`,
      t6: `<table class="vs-t"><thead><tr><th>Criterio</th><th>Agencia Branding</th><th>Consultor</th><th class='vk'>STUDIO PRO</th></tr></thead><tbody><tr><td>Custo mensal</td><td>R$4.970-15.000</td><td>R$3.000-8.000</td><td class='vk'>R$1.230-1.490</td></tr><tr><td>Producao mensal inclusa</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Brandbook com IA</td><td class='vn'>✗ Nao</td><td class='vn'>✗ Nao</td><td class='vk' class='vy'>✓ Sim</td></tr><tr><td>Comite mensal</td><td class='vn'>✗ Paga extra</td><td class='vy'>✓ Sim</td><td class='vk' class='vy'>✓ Incluso</td></tr></tbody></table>`,
    },
  },
};
