ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS client_approval_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE task_comments
  ADD COLUMN IF NOT EXISTS is_approval_evidence BOOLEAN NOT NULL DEFAULT FALSE;
